.travis.yml
Hi there!
I added an initial configuration for travis-ci. I disabled tests for non-gcc compilers as they fail at the moment.
I think mingw32 should be added, too. Maybe appveyor.com and coveralls.io could be added. ;-)
OpenSSL uses mingw32:
https://github.com/openssl/openssl/blob/master/.travis.yml
You need to create a free travis account and enable ccache repository on your profile page: https://travis-ci.org/profile/
=> Add initial travis config

MANUAL.txt, NEWS.txt, ccache.c, test.sh
This is relevant in the light of global activation of ccache and global setting of CCACHE_HASHDIR:
https://bugzilla.redhat.com/show_bug.cgi?id=759592
By relocating the gcc debuginfo (similar to relocating source with CCACHE_BASEDIR),
it should be possible to still get cache hits even when generating debugging information...
=> Debuginfo and -fdebug-prefix-map

Makefile.in, configure.ac, dev.mk.in, m4/clang.m4, src/ccache.c, src/ccache.h, src/cleanup.c, src/compopt.c, src/conf.c, src/hash.c, src/hashtable.c, src/hashtable.h, src/hashtable_itr.c, src/hashtable_itr.h, src/hashtable_private.h, src/language.c, src/snprintf.c, src/stats.c, src/unify.c, src/util.c, unittest/framework.c, unittest/framework.h, unittest/main.c, unittest/test_compopt.c, unittest/test_conf.c
`./configure --enable-more-warnings`
Address most warnings, except those about conversion between float/double and int32_t/int64_t.
We also get some warnings from included system headers, that we need to suppress (for `-Werror`)
Now passes `gcc -Wextra` (including pedantic) and `clang -Weverything` (with some exceptions)
=> Add option for enabling more compiler warnings

src/conf.c
Both strdup and format are returning "char *"
```
src/conf.c:642:22: error: cast from 'const char *' to 'char *' drops const qualifier [-Werror,-Wcast-qual]
char *str = (char *)item->formatter(value);
^
src/conf.c:659:22: error: cast from 'const char *' to 'char *' drops const qualifier [-Werror,-Wcast-qual]
char *str = (char *)item->formatter(value);
^
```
=> Fix const-correctness of the config formatter

src/unify.c
`no previous prototype for function 'unify_hash'`
When running with `--enable-more-warnings` that is
=> Fix missing header include / prototype

src/ccache.c, test/suites/hardlink.bash
When using assembler, clang doesn't unlink output.
On the other hand, gcc seems to handle this fine ?
Closes #331
=> Handle bug where clang doesn't unlink output file

src/ccache.c
Currently, ccache supports calculating relative path
for 1 level non-exist path. That is to say,
if the given path does not exist, however if its
parent directory exists, then ccache can calculate
the relative path correctly.
Unfortunately this doesn't fit the needs.
Xcode build system always adds these paths into header search path:
xxxxx/DerivedResources/x86-64
xxxxx/DerivedResources
these paths are build outputs for build rules.
For projects which doesn't use build rule to generate files
these directories do not exist.
So this change refine the logic of make_relative_path 
to recursively go up find the nearest existing directory
and use the remaining path as path_suffix.
=> Handle several levels of nonexistent directories in make_relative_path

doc/MANUAL.adoc, src/ccache.c, src/ccache.h, src/confitems.c, unittest/test_conf.c
This option is used to enable 'Indexing while Building' in Xcode9,
which does not affect the build output.
The reason we have to skip it is it introduces a path contains
uuid, for example:
-index-store-path /Users/lanya/Library/Developer/Xcode/DerivedData/NEUer-bjvoyplxzoxgkpgkiodfvurkgzwn/Index/DataStore
This causes build command is different between builds. So skip it in manifest hashing.
=> Skip '-index-store-path' when building with Xcode

dev.mk.in
Missed to include this, when making compilation optional
Closes #340
=> Add missing getopt_long.c source file to dist

configure.ac
Don't hardcode the clang version, apparently clang-3.8
did have the warning even though clang-3.4 did not...
=> Fix clang warning with older compiler versions

configure.ac, src/lockfile.c, src/system.h
ccache building was broken on IBM i/PASE.
PASE is the Unix subsystem within IBM i (which is a development of the legacy OS/400 product line). PASE is binary compatible with AIX, however, subtle differences exist due to the operating system not being Unix-like _at all_. Applications which compile and run also run on IBM i, and most source trees which build on AIX will also build on IBM i.
The build was broken on IBM i for two reasons:
_ar needs -X64 on AIX and i_
`ar` on AIX and IBM i needs to explicitly define if the archive being created is for 32 or for 64 bit code. When this parameter is not specified, `ar` on AIX and IBM i fails hard without any output since GCC on AIX and IBM i does not rely on binutils for `ld` and `ar`.  I have updated the `configure.ac` script to check if it's …
=> Fix the build on IBM i / PASE

src/ccache.c
One of the slow things for incremental Linux kernel builds is that
during the single-threaded parsing stage of the Makefile the kernel
calls into the C compiler to test which options the compiler supports.
A lot.  Specifically there are snippets like this all over the
Makefile:
$(call cc-option,-Oz,-Os)
...which translates into a call to the C compiler:
${CC} ... -Oz -c -x c /dev/null -o .178435.tmp
One of the contributing factors to the overall slowness is that the
input file for this test is "/dev/null".  This trips a check in ccache
because "/dev/null" "isn't a plain file".
As far as I understand it it should be totally fine to cache the
result of compiling "/dev/null".  It's basically just compiling an
empty file.
On my setup this improves the parsing stage of the kernel Makefile
from …
=> Allow treating "/dev/null" as an input file

src/ccache.c, test/run, test/suites/depend_different_headers.bash
This was previously only done if preprocessor was run.
=> Support multiple versions of dependencies per one manifest

src/ccache.c, test/suites/depend.bash
This was previously only done if preprocessor was run.
Added test case.
=> Enable generating relative paths in dependency file in depend mode.

src/ccache.c
Recently I landed commit 980e032d14ba ("Allow treating "/dev/null" as
an input file (#365)") which sped up my kernel build a bunch.
Unfortunately I tested my change in isolation on the newest ccache
(AKA I constructed a simple test case and saw that it worked).  I only
tested it together with the Linux kernel when backported to an older
version of ccache.  A bit later I managed to get the newer version of
ccache fully integrated into my build system and tested my path there.
Then I noticed a problem because the new ccache contained the commit
919af39ccaca ("Support gcc-8 -ffile-prefix-map")
Specifically my compiler doesn't support the
-fmacro-prefix-map=... option and thus my change and the ccache change
to support -fmacro-prefix-map caused caused my kernel build to fail.
It couldn't …
=> Include the presence of "-fxxx-prefix-map=" options in the hash

src/ccache.c, test/suites/hardlink.bash
The depends are small enough to avoid the copy, since it leads
to issues with mv when using automake to generate the Makefile.
Closes #378
=> Copy rather than link depend from the cache

src/minitrace.c, src/minitrace.h
Reported buffer size upstream as: https://github.com/hrydgard/minitrace/issues/16
=> Upgrade minitrace to latest master

src/ccache.h, src/execute.c, src/hashutil.c
the @file syntax means that the process reads command arguments from the
specified file. this is commonly used in order to shorten commands which
would otherwise be longer than the maximum length limit: many build systems
do this in all cases to avoid hitting this limit.
when a command exceeds 8192 characters on on Windows, ccache now writes
the parsed/modified arguments to a tmpfile and then runs the command using
that tmpfile with @tmpfile in order to preserve this mechanism and avoid hitting
the length limit
fixes #95
=>  correctly handle @file syntax on Windows

src/ccache.c
With -fprofile-*=path, we currently print :
"Setting profile directory to (null)".
This fixes the build with gcc 9, which failed with :
error: ‘%s’ directive argument is null [-Werror=format-overflow=]
=> Fix NULL argument in profile directory trace

doc/DEVELOPER.md, doc/NEWS.adoc, m4/feature_macros.m4, src/conf.c
Found via `codespell -q 3 -L uint,thru -S ./src/zlib`
=> Misc. source comment and documentation typos

src/ccache.c, src/stats.c
There are global variables used for updating stats,
and those were wrong for the manifest file update.
So make sure to reset those variables, before adding
the manifest (this means flushing the pending updates)
Closes #402
=> Update the correct stats file, for manifest

src/ccache.c, src/hashutil.c, src/hashutil.h, src/manifest.c, src/manifest.h, test/suites/depend.bash, test/suites/direct.bash
Changed manifest format to save the actual file size along with hashed content size.
File size field in manifest updated to 64bits.
Manifest version set to 2.
Fixes #382.
=> Fix object size verification

configure.ac, doc/MANUAL.adoc, misc/rsyslog.d/00-ccache.conf, src/util.c
The file logger has some issues with large log lines and many jobs,
so provide the "syslog" alternative when doing the ccache logging.
For #350
=> Implement optional logging to syslog

src/compopt.c
It produces extra .json file with timing information about the compilation.
(https://aras-p.info/blog/2019/01/16/time-trace-timeline-flame-chart-profiler-for-Clang/)
=> clang's -ftime-trace is too hard

doc/MANUAL.adoc, src/ccache.c, test/suites/pch.bash
(I can split this if you dislike so many commits, but it mostly belongs together. I was looking for the PCH bug and had to extend the tests quite a bit before I finally found it.)
This fixes ccache failing to hash pch file in depend mode if that pch file is introduced only using -include. The rest is adding more PCH tests and removing the needless duplication between GCC and Clang.
=> Fix PCH detection in depend mode (+test improvements)

src/ccache.c
We might need it for the alternate codepaths
If not using a standard file store, it might
not be possible to move stderr instead of copy.
For those cases, use the temporary file instead.
---
_Broken out from #408, if not ready for all of it_
_This just restructures the code, for extending..._
_By doing it separately like this, ahead of time,_
_the other changes need to modify less things_
=> Refactor: save tmp stderr until done storing

src/manifest.c
cppcheck:
[src/manifest.c:270] -> [src/manifest.c:269]: (warning)
Either the condition '!errmsg' is redundant or there is possible null pointer
dereference: errmsg.
PR fixes possible NULL pointer dereference found by cppcheck
=> Fix possible NULL pointer dereference

Makefile.in, configure.ac, src/compr_zstd.c, src/compression.c, src/compression.h, src/conf.c, src/decompr_zstd.c, src/result.c, unittest/test_compr_zstd.c, unittest/test_conf.c
This is the version without the zlibWrapper, using native zstd as a compression implementation.
See #413 (and #436)
=> Allow using zstd compresssion instead of zlib

Makefile.in, src/ccache.c, src/ccache.h, src/common_header.c, src/common_header.h, src/compress.c, src/manifest.c, src/manifest.h, src/result.c, src/result.h
This will only show information about the files that is knows about
(right magic bytes). So the file count might differ from what is shown
with the regular statistics (which shows all files, including old ones).
The terminology used here is a bit confused, the compression ratio is
supposed to grow upwards. Sometimes known as "space savings" instead,
so list both values (ratio and savings) to make the output more obvious.
=> Add command to show compression statistics

src/lockfile.c, test/run, test/suites/base.bash, test/suites/basedir.bash, test/suites/debug_prefix_map.bash, test/suites/masquerading.bash, test/suites/upgrade.bash, unittest/test_lockfile.c
Installed `msys2-x86_64-20161025.exe`, with `gcc` and `make` (using `pacman`).
After some fixes, it runs in Unix mode (Cygwin). Windows mode (MinGW) left to do.
Most issues were related to symlinks.
Closes #170 
```
unittest/run.exe
PASSED: 484 assertions, 95 tests, 10 suites
CC='gcc' /bin/sh ./test/run
Compiler:         gcc (/usr/bin/gcc)
Compiler version: gcc (GCC) 6.4.0
CUDA compiler:    not available
Running test suite base.......................................................
Running test suite nocpp2.......................................................
Running test suite cpp1.
Skipped test suite multi_arch [multiple -arch options not supported on MSYS_NT-6.1]
Skipped test suite serialize_diagnostics [--serialize-diagnostics not supported by compiler]
Running test suite …
```
=> Added remaining changes, to make it run on MSYS

dev.mk.in
Apparently gperf doesn't like DOS linefeeds
As observed when testing PR #170
=> Fix gperf generation when running on MSYS2

src/ccache.c, src/language.c, test/suites/nvcc.bash
Hi, I was trying to use ccache from a CMake project to compile CUDA files and ran into two issues:
First, CMake always passes `-x cu` to NVCC. This is recognized by ccache as an explicit language setting, but the language "cu" is not understood by ccache. The first commit add the "cu" language as an alias to "cuda".
Second, we use [separable compilation](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#using-separate-compilation-in-cuda) which requires CMake to pass the `-dc` or `--device-c` option. This option as stated [here](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-specifying-compilation-phase-device-c) implies the `-c` option already.
Previously, the `-c` option was missing and ccache didn't cache the compiled files. The second …
=> Improve CMake+CUDA compatibility: add "cu" language, recognize -dc as compilation only argument

configure.ac
Updates libzstd to [v1.4.3](https://github.com/facebook/zstd/releases/tag/v1.4.3)
Confirmed that `make check` passes on Linux x86_64
=> configure: Update libzstd to 1.4.3

src/result.cpp
The stack variable `suffix` is not guaranteed to be zero-terminated.
=> Fix an out-of-bounds read when logging

test/run
test output: improve readability on light backgrounds
`bold()` now only writes bold text, not bold and white text
_and_
test output: only use ansi codes when run in a terminal
=> Test output: visibility on light backgrounds / ansi codes

configure.ac
Fixes the warning `../configure: line 2250: src/version.cpp: No such file or directory` when doing out of source build.
=> Fix warning during configure in out of tree build

src/ccache.cpp, src/result.cpp, src/result.hpp
As discussed in #473, feel free to adapt the enum name or the enum entries to your liking. E.g. to me it was very important that stderr_output had the id 2!
=> Convert result type string to an enum

src/FormatNonstdStringView.hpp, unittest/test_Util.cpp
Empty string_views could not be handled and formatting
did not stop until the first \0 was encountered.
=> Fix and test interaction between fmt and nonstd::string_view

src/ccache.c, src/compopt.c, unittest/test_compopt.c
Added test to detect the invalid case TOO_HARD | TAKES_CONCAT_ARG
=> Correct "-MJ" bail out, identify both "-MJ file" and "-MJfile"

doc/MANUAL.adoc, src/Config.cpp, src/ccache.cpp, src/ccache.hpp, src/compopt.cpp, src/stats.cpp, test/run, test/suites/modules.bash
Clang creates the internal on-disk representation of modules
in the background on demand as necessary. This means that ccache does
not need to cache that, all that it needs to cache is the actual
compilation result and the dependencies. Which in the case of modules
includes also the module.modulemap files, and Clang outputs such
dependencies correctly only in the depend mode, in the preprocessed
output there is no way to find out the module dependencies.
Therefore support -fmodules in direct depend mode by more or less
ignoring it. Tested with source build of LLVM/Clang configured
with -DLLVM_ENABLE_MODULES=On (and the build actually occassionally
fails because of module problems, but that happens regardless of ccache).
See also pull request #130 (and this reuses the tests from there). …
=> Allow -fmodules in direct depend mode

src/ccache.cpp
Compiler invocation in the depend mode uses the original arguments,
which means the added -fcolor-diagnostics (or -fdiagnostics-color)
was dropped.
=> Handle properly color diagnostics also in depend mode

configure.ac, doc/MANUAL.adoc, src/hashutil.cpp, src/hashutil.hpp, src/macroskip.hpp, unittest/test_hashutil.cpp
`__TIMESTAMP__` is [expanded by the pre-processor](https://github.com/gcc-mirror/gcc/blob/master/libcpp/macro.c#L397) to `asctime()` of the source file's modification time. Handle `__TIMESTAMP__` similar to `__DATE__` and include asctime(modification time) in the hash when `__TIMESTAMP__` is detected in the source code.
=> Add handling of __TIMESTAMP__ macro

src/CacheEntryWriter.hpp, src/CacheFile.hpp, src/Compressor.hpp, src/File.hpp, src/FormatNonstdStringView.hpp, src/NullCompressor.hpp, src/NullDecompressor.hpp, src/ProgressBar.cpp, src/ProgressBar.hpp, src/cleanup.hpp, src/compress.hpp, src/legacy_util.cpp, src/system.hpp
Set the _WIN32_WINNT macro only once in the generated config.h.
Include <windows.h> only once in system.hpp, unless these includes
are in third party libs - however third party includes themselves
should always be behind internal includes.
=> Windows define and include restructuring

src/Config.hpp, src/Util.cpp, src/Util.hpp, src/ccache.cpp, src/ccache.hpp, src/execute.cpp, src/hash.cpp, src/hash.hpp, src/legacy_util.cpp, unittest/test_Config.cpp, unittest/test_Config.hpp, unittest/test_Util.cpp, unittest/test_legacy_util.cpp
Misc string view stuff I came across, split into separate commits.
Also, what is your opinion on adding `using nonstd::string_view;` to the top of `.cpp` files?
=> Misc C++-ification

src/Util.cpp, unittest/test_Util.cpp
Remove manual int boundary checks as std::stoi already does that (throws out_of_bounds in that case)
=> Simplify parse_int slightly

test/run
When the test suite fails 'testdir.failed' now points to the random
'testdir.9876/'  directory. This make iterative debugging of failing
tests easier by always using the symlink name or re-issuing 'cd $PWD'
when 'cd'-ed into the 'testdir.failed' directory.
All artifacts can still be removed via 'rm -r testdir.*'.
=> Failed tests create a testdir.failed symlink

src/stats.cpp
If a stats file update for some reason fails, the exception will bubble up to ccache_main which just prints the error and exits with an error. Let’s consider such failures non-fatal and just log them.
=> Make failure to write a stats file a soft error

dev.mk.in
Now that most .cpp has a .hpp (since: Split ccache.hpp into per-.cpp file headers)
=> Derive header list from source list if possible

src/Config.cpp, src/Config.hpp, src/ccache.cpp
Prevents changes from getting lost by writing them to a
temporary copy of the main Config object.
Also restore deleted comments from the move of
primary/secondary_config_path.
=> Make Config noncopyable and add clear_and_reset() method

Makefile.in, dev.mk.in, src/ArgsInfo.cpp, src/ArgsInfo.hpp, src/ScopeGuard.hpp, src/args.cpp, src/args.hpp, src/ccache.cpp, src/ccache.hpp, src/legacy_globals.cpp, src/legacy_globals.hpp, src/legacy_util.cpp, src/legacy_util.hpp, src/manifest.cpp, unittest/test_ScopeGuard.cpp, unittest/test_Util.cpp, unittest/test_argument_processing.cpp, unittest/test_legacy_util.cpp
plus
Simplify make_relative_path() argument and result ownership
because all the make_relative_path(x_strdup(..)) + free() calls were getting out of hand.
=> Make cc_process_args() only use local variables

src/ccache.cpp
Repeated initialize-calls in ccache_main_options() added duplicate exit
functions. These calls had the side effect of passing a config relevant
changes from one command line switch to the next. Instead setup_config()
is now called afterwards.
=> Extract setup_config() from initialize()

Makefile.in, src/Context.cpp, src/Context.hpp, src/ccache.cpp, src/exitfn.cpp, src/legacy_globals.cpp, src/legacy_globals.hpp, src/logging.cpp, src/logging.hpp, unittest/test_argument_processing.cpp
As discussed in #526, the Context argument is now only added as-needed.
=> Add Context, move two globals into in

src/args.hpp
The CPPFLAGS contain "-I.", but not "-I$(srcdir)", which means "src/ScopeGuard.hpp" was only
found when building from the source root.
=> Fix out of tree build

dev.mk.in, misc/clang-format.sh
clang-format has no option to change the exit code, so
check manually. Additionally, clang-format < 9 updates
timestamps of all checked files, this works around that.
=> Added 'make check_format' to makefile rules

src/ccache.cpp, src/legacy_globals.cpp, src/legacy_globals.hpp, unittest/test_argument_processing.cpp
No function signature changes and rather straightforward, minus the (already-used) convention that testing for `nullptr` becomes `string::empty()`.
The last `ArgsInfo` global `output_is_precompiled_header` is more complex and will be done after `g_config` is moved, which is next.
=> Context: move 9 more globals

dev.mk.in, src/Util.cpp, src/ccache.cpp, src/compress.cpp, src/legacy_util.cpp, src/result.cpp, src/stats.cpp, src/stats.hpp
Make it possible to run `make format|check_format|cppcheck` in out-of-tree builds. Also fix some of the warnings reported by cppcheck.
=> Out of tree commands

test/suites/fileclone.bash
Two fileclone tests rely on the output.
=> Restore test suite debug output where needed

src/hashutil.cpp, src/hashutil.hpp, src/manifest.cpp
hash_source_code_string will, in read_file, stat the file to get the file
size. But when called from verify_result, the file size is already known so by
using this size the number of stat calls in a normal run can be cut in half.
=> Avoid duplicate stat calls

dev.mk.in
Also print only diff to stdout, fix tabs
(And oversight from db6706ad3b5)
=> Make check_format exit with the appropriate status

src/ccache.c, src/language.c, test/suites/nvcc.bash
Backport https://github.com/ccache/ccache/pull/381
I ran into various "Illegal instruction" issues on CI servers with libzstd on v4 branch. It would be advisable if ccache could compile libzstd such that it doesn't optimize for the cpu features present on the machine performing the compilation.
In the meantime, it's helpful to backport this fix to the 3.7 branch.
=> Backport cuda fixes to v3.7 branch

src/conf.c
Verified manually (on linux only):
./ccache --set-config=cache_dir_levels=5
./ccache --set-config=base_dir=/tmp
./ccache --set-config=max_size=5G
./ccache --show-config
./ccache --set-config=cache_dir_levels=3
./ccache --set-config=base_dir=/home/alex
./ccache --set-config=max_size=15G
./ccache --show-config
Before this patch it would fail with:
* cache_dir_levels was comparing pointer to <= 8 --> cache directory levels must be between 1 and 8
* base_dir was comparing jibberish with is_absolute_path --> not an absolute path
Those are the only two validations done on config input, therefore I verified with max_size that nothing else got broken here.
//edit: there is no automatic link created from title or commit messages, so here we go: #559 😄
=> Fix #559 (setting base_dir and cache_dir_levels)

.clang-tidy, .travis.sh, .travis.yml, src/.clang-tidy, src/Counters.cpp, src/logging.cpp, src/third_party/.clang-tidy, unittest/.clang-tidy
Add clang-tidy (and check_format) to CI to prevent regressions.
Over time more checks could be enabled as they are fixed in code.
Some checks might require further configuration, this can be done over time.
Important: some checks are style/opinion based. Enabling all of them is not the point!
P.S. I have no idea what .travis.sh is used for. I've added something there too.
=> Enable check_format and clang-tidy checks in CI

m4/feature_macros.m4, src/ProgressBar.cpp
These changes enable building on Oracle Solaris 11.4 for both i386 and sparc.
=> Make ccache build on Solaris 11.4

test/suites/base.bash
Since I actually managed to screw this up, it seems it's worth a test :-)
It's currently not testing that much... just that it's not random memory being dumped into the version string. But that's more than before.
=> Add test for human readable version output

dev.mk.in, misc/check_format.sh, misc/format.sh, misc/run-clang-format
This way it is executable without running configure first.
Formatting is in no way dependent on running autogen/configure/cmake/make.
Which will in turn simplify CMake transition as CMake does not need to support that.
This commit preserves `make check_format` and `make format` targets.
In addition formatting is executable via `misc/check_format.sh` and `misc/format.sh`.
=> Extract formatting logic from make.

test/suites/hardlink.bash
AFS _kind of_ supports hardlinks, but not really - you can't make hardlinks across directories, only within them. This basically defeats the point of the ccache hardlink mode - the only way to use it would be if your cache directory is the same as your compilation directory, which is silly. Unfortunately the current hardlink probe doesn't test this case and proceeds with the test suite anyway, which fails.
=> Disable hardlink testing on AFS

dev.mk.in
The escape sequence '\n' should be translated to a new line character
when printed to version.cpp. Default mode might be implementation
dependent, thus add the command line switch to make it portable. At
least in Fedora /usr/bin/echo defaults to -E.
=> Don't depend on how echo interprets backslash escapes

src/argprocessing.cpp, src/ccache.cpp, test/suites/profiling_clang.bash
Add support for -fprofile-sample-use and -fprofile-sample-accurate.
=> Support clang options for compiling with sampled profiles

doc/MANUAL.adoc
The ccahce over NFS and different OS version behavior is documented. The probable solution is also suggested (by enabling system_headers in sloppiness).
=> Documentation change for cache over NFS

src/InodeCache.cpp, src/hash.cpp, src/hash.hpp, unittest/test_hash.cpp
Add hash_buffer_once method for hashing a given text immediately using a
stack allocated hasher. Also skip copying the hasher in hash_result as
blake3 is not modifying the hasher.
=> Reduce number of memory allocations in hashing

ci/build
Tested with CTest parameter `--repeat-until-fail 50` locally, locally in docker and on [travis](https://travis-ci.com/github/AlexanderLanin/ccache/builds/172374665). No random problems encountered (Besides Travis killing the MacOS job after a 50 minute timeout).
While this is "only nice" for daily work, it's critical for testing multiple images with docker as the runtime is just too long otherwise.
=> Run compilation and tests with multiple threads

src/Util.cpp
Don't log "Unlink failed: Success" on failure.
=> Util::unlink_tmp: Log with correct errno

src/ResultDumper.hpp, src/ResultExtractor.hpp, src/ResultRetriever.hpp, src/third_party/fmt/core.h
This change is required to make ccache compile with clangs trunk version. It seems they improved the "missing override" warning.
The change within fmt is reported as https://github.com/fmtlib/fmt/pull/1836
If we do not want to change fmt directly we could instead disable the warning via CMakeLists or upgrade to fmt trunk version.
=> Fix override usage

CMakeLists.txt
I stumbled upon this due to a new setup.
Turns out CMake requires ASM to be the last parameter so it can try whether the C compiler can compile asm.
See https://gitlab.kitware.com/cmake/cmake/-/merge_requests/1560/diffs
This might be not 100% accurate, it's from memory:
1. Install Ubuntu 18.04
2. `sudo apt update`
3. `sudo apt upgrade`
4. `sudo apt install clang-10`
5. `sudo ln -s /usr/local/bin/c++ /usr/bin/clang++-10`
6. `sudo ln -s /usr/local/bin/cc /usr/bin/clang-10`
And out of desperation:
7. `sudo apt install build-essential`
```
-- The ASM compiler identification is unknown
-- Found assembler: /usr/local/bin/cc
-- The C compiler identification is Clang 10.0.0
-- The CXX compiler identification is Clang 10.0.0
-- Warning: Did not find file Compiler/-ASM
-- Check for working C …
```
=> Fix asm compiler detection

.gitignore, CMakeLists.txt, LGPL-3.0.txt, LICENSE.adoc, cmake/GenerateConfigurationFile.cmake, cmake/StandardSettings.cmake, cmake/StandardWarnings.cmake, cmake/config.h.in, misc/format-files, src/Args.cpp, src/CMakeLists.txt, src/Lockfile.cpp, src/ProgressBar.cpp, src/Result.cpp, src/Util.cpp, src/Util.hpp, src/Win32Util.cpp, src/ZstdCompressor.cpp, src/ccache.cpp, src/system.hpp, src/third_party/CMakeLists.txt, src/third_party/win32/getopt.c, src/third_party/win32/getopt.h, test/CMakeLists.txt, unittest/TestUtil.hpp, unittest/test_Stat.cpp, unittest/test_Util.cpp, unittest/test_argprocessing.cpp
With these changes, the project builds with Visual Studio 2019, unit
tests pass and it works correctly with mingw gcc.
NOTE: The very latest version of Visual Studio 2019 is required, because
there was just a necessary fix for template arguments.
Tested building and running unit tests on Windows+MSVC, Windows+MinGW,
Linux and macOS.
- Enable `ZSTD_FROM_INTERNET` by default for MSVC when not using vcpkg
or conan.
- Add include tests for some standard UNIX headers not available on
MSVC.
- Add necessary MSVC compiler flags.
- In `Args::from_gcc_atfile()` iterate over the string via `c_str()`
instead of `cbegin()`, the MSVC string character iterator does not
include the ending null byte.
- Misc. minor cmake fix-ups.
- Add some headers that are not implicitly included from other headers
like …
=> Support building on MSVC.

.github/workflows/build.yaml, cmake/StandardSettings.cmake
* Seems reasonable to have less builds.
* The concatenation of multiple sanitzers was actually wrong.
* I was going to enable memory sanitizer in the other job but failed due to https://github.com/onqtam/doctest/issues/414
=> Merge address and UB sanitizer

.gitignore
Visual Studio 2019 builds into /out/ directory. The only way to change that is by adding yet another file named CMakeSettings.json. Adding the default to gitignore seems simpler.
Use Case: running unittests through Visual Studio due to its great debugger.
=> Add Visual Studio build directory to gitignore

src/argprocessing.cpp, src/argprocessing.hpp, src/ccache.cpp, unittest/test_argprocessing.cpp
Using return instead of out-parameters simplifies reasoning about the code. And also usage.
Refactoring done based on [F.21: To return multiple "out" values, prefer returning a struct or tuple](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f21-to-return-multiple-out-values-prefer-returning-a-struct-or-tuple)
=> Refactoring: use return syntax for process_args

unittest/test_argprocessing.cpp
Assuming Args has (or gets 😉) an internal state, this is not what these tests should compare. They do not care about comparing the internal representation of Args, so it doesn't make sense to convert both sides to Args. Instead these tests care about what happens when Args are serialized to a string. Usually via to_argv, but to_string is way more convenient to use here.
Note: Alternatively operator== could be maintained to compare in such a way. But it always gets difficult then what exactly that operator compares as equal.
Note: This is a small innocent commit which improves the codebase insignificantly. It should not be difficult to review and should not have any disadvantage. It prepares for a bigger change of Args and Arg. Regardless of whether that last PR is accepted or not, this …
=> Tests: Compare relevant part, not internal state

unittest/test_argprocessing.cpp
There is currently no unittest for testing parsing of -Xclang paramaters.
Expected output is reverse engineered form current implementation.
=> Test: introduce unit test for -Xclang argument

src/Util.cpp, src/Util.hpp
The change is small, but once you start using string_view all those small functions have to use string_view as well. Otherwise a string needs to be created out of a string_view just to be discarded a second later.
(Compiler may be able to optimize it away if the function would accept a string object, but using string_view seems cleaner and is more in line to the other functions)
'+ Add some constness in the surrounding lines since we are touching the file anyway.
=> Refactor: convert Util function to use string_view

src/Config.hpp, src/Util.cpp, src/Util.hpp, src/ccache.cpp, src/ccache.hpp, unittest/CMakeLists.txt, unittest/test_ccache.cpp
Since fixing #432 is surprisingly complex as witnessed in #664, this documents current behavior of find_compiler in detail.
Besides helping in development this allows talking about how it should behave in the future.
No functional changes.
=> Add unittest for find_compiler

cmake/Findzstd.cmake
I encountered problems downloading zstd due to a proxy and got no helpful information from the current cmake script whatsoever since it did not evaluate exit codes.
=> Add error detection to zstd download

src/argprocessing.cpp, src/ccache.cpp, src/compopt.cpp, src/compopt.hpp, unittest/test_compopt.cpp
This is a small almost insignificant change.
I was wondering what those functions do, so I improved their names slightly.
+ Tests are cleaned up to less test cases + some border cases added.
I made separate commits for trivial review 👍
I was actually looking into the argument type those functions receive (string, string_view or char*), but that got a little out of hand so I wanted to get this trivial part merged first.
=> Refactor: slightly improve naming in compopt

src/argprocessing.cpp, unittest/test_argprocessing.cpp
Add unittests and simplify logic for parsing -x.
Logic is simplified in the sense that if first enters the "-x" case and then does the rest. This becomes important in case of adding any argument parser where "-x" is a registered key.
Note: There are two separate commits. First one only adds tests. Tests are green. Second one changes the actual code.
=> Add unittests to parsing -x

src/ccache.cpp, test/suites/base.bash, unittest/test_ccache.cpp
This makes ccache always use `compiler` from its config when it is set.
Resolves #432
Note: the function structure had to change significantly because there was a return statement right in the middle of it and the functionality is actually changed a lot in detail (see unit tests).
=> Make CCACHE_COMPILER always the highest priority

test/suites/profiling.bash, test/suites/profiling_gcc.bash
Fixes a failure seen in `make check` when updating ccache to 3.7.12 in conda-forge (https://github.com/conda-forge/ccache-feedstock/pull/17):
```
Running test suite sanitize_blacklist...
ld: library not found for -lgcov
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
./test/suites/profiling.bash: line 79: ./test: No such file or directory
error: data/*.profraw: No such file or directory
error: Could not read profile data/default.profdata: No such file or directory
1 error generated.
Running test suite profiling.....
FAILED
```
I didn't manage to figure out why this change was made, but I think the GCC specific code should have been isolated to `profiling_gcc.bash` instead of also being included in `profiling_.bash`. In the conda-forge update this patch …
=> Remove -lgcov from compiler independent profiling script

test/run
Test case CCACHE_UMASK fails when running it in Fedora because /bin/ls
adds a trailing dot to the output. Thus truncate the output to expected
length.
=> Fix expect_perm to work with SELinux

src/third_party/blake3/CMakeLists.txt
The .S file does not compile with clang 3.4 and 3.5.
It seems it's only some optimization and we can as well trivially fall back to the C version.
(Not tested with clang 4, so let's just apply the fallback to anything before 5.0)
This is probably relevant for #689 for the older MacOS versions since they use clang 3.4 by default.
=> Blake3: use C version on ancient clang

cmake/GenerateConfigurationFile.cmake, src/hashutil.cpp, src/third_party/blake3/CMakeLists.txt, src/third_party/blake3/blake3_cpu_supports_avx2.h, src/third_party/blake3/blake3_dispatch_ccache.c
Instead of relying on the sometimes broken __builtin_cpu_support. This hopefully also fixes the build error on Mac OSX 10.11 reported in a comment in #689.
This exposes an internal detail of BLAKE3, but it's hopefully a small change that shouldn't cause problems when upgrading BLAKE3.
=> Use BLAKE3 machinery for detecting AVX2 support

src/Util.cpp
=> Require CLONE_NOOWNERCOPY to be defined for clone on mac

src/third_party/CMakeLists.txt
Fix order of commands in third_party cmake
fixes #697
@mumpitzstuff can you try whether this resolves your issue? Unfortunately I cannot try MSVC myself right now. I assume you have the problem with MSVC.
=> Fix order of commands in third_party cmake

CMakeLists.txt
As suggested in #695 by @ryandesign ccache compilation should fail with a human readable error in case of unsupported compilers.
This would technically close #695.
=> Fail gracefully on ancient compilers

.github/workflows/build.yaml, CMakeLists.txt
Currently CI runs with:
Part 1:
ubuntu-16.04-gcc-5.5.0
ubuntu-16.04-clang-9.0.1
ubuntu-18.04-gcc-7.5.0
ubuntu-18.04-clang-9.0.0
ubuntu-20.04-gcc-9.3.0
ubuntu-20.04-clang-10.0.0
macos-10.15-gcc-11.0.3 (or is it clang, apple clang or xcode?)
macos-10.15-clang-11.0.3 (or is it clang, apple clang or xcode?)
Part 2:
ubuntu-16.04-gcc-4.8.5
ubuntu-18.04-i686-w64-mingw32-gcc-posix (GCC) 7.3-posix
ubuntu-18.04-x86_64-w64-mingw32-gcc-posix (GCC) 9.3-posix
(Determined via adding `${{ matrix.config/compiler.CC }} --version` to build.yaml)
This is less then obvious from build-yaml. And while it runs lots of jobs it doesn't cover as much as it could by carefully selecting the exact os - compiler combinations.
=> CI: list all configurations explicitly

cmake/CcacheVersion.cmake
I was just looking into clang 3.4 and noticed the following strange behavior: cmake command failed due to missing git.
How to reproduce:
1) change ubuntu-14.04/Dockerfile from clang to clang-3.4
2) `CC=clang CXX=clang++ CMAKE_PARAMS="-DZSTD_FROM_INTERNET=ON" misc/build-in-docker ubuntu-14.04`
It fails since git is not installed into the docker image. Why should it? I'm quite fine with not knowing the git hash within docker.
=> Fall back to version "unknown" when Git is not installed

dockerfiles/ubuntu-14.04/Dockerfile, test/suites/modules.bash, test/suites/profiling.bash, test/suites/profiling_clang.bash, test/suites/profiling_hip_clang.bash, test/suites/sanitize_blacklist.bash, test/suites/serialize_diagnostics.bash, test/suites/split_dwarf.bash
We need to disable/fix some tests on clang 3.
Unfortunately clang 5 is also affected.
(Currently not tested with clang 4)
This is definitely not pretty and I would appreciate a better fix!
Discovered in #690 and probably relevant for #689 since the old MacOS versions are using AppleClang based on clang 3.4.
=> Disable some tests on ancient Clang versions

cmake/StandardSettings.cmake, cmake/StdAtomic.cmake
Linking with libatomic is apparently needed when using `<atomic>` functionality with GCC on ARM and PowerPC.
Fixes #720 and fixes #721.
=> Link with libatomic when needed

src/ccache.cpp, src/ccache.hpp, unittest/test_ccache.cpp
**Problems**
`result_name_from_depfile` is simply split depfile content with a space
which breaks the file path contains a space, which is often happening
on Apple platform developments such as iOS application.
Currently if users are using `ccache` with a file located in a path with a space like
`path/with/a/space may/fail`, the log may contains following errors:
```
[2020-11-04T10:08:41.118646 54991] Disabling direct mode
[2020-11-04T10:08:41.118667 54991] Failed to stat path/with/a/space\: No such file or directory
[2020-11-04T10:08:41.118679 54991] Failed to stat may/fail: No such file or directory
...
```
**Solution**
Parse depfile by taking care of escaped characters.
A depfile that compilers generate is in Makefile format which may
contain escaped characters by the backslash, …
=> Fix result_name_from_depfile by parsing depfile in Makefile syntax

.github/workflows/build.yaml
Without update, apt tries to download outdated packages, which possibly
don't exist.
=> Github: Call apt-get update before install

.github/workflows/build.yaml, CMakeLists.txt
The release contains only the executable without the dll dependencies.
It is easier to deploy a single self-contained executable anyway.
Fixes #729
=> MinGW: Default to static linking

cmake/GenerateConfigurationFile.cmake, src/third_party/blake3/CMakeLists.txt
Improve detection of SSE/AVX by trying to compile a short code snippet with some intrinsic from the feature that is tested for. Fixes #734.
Add support for detecting Neon support on AArch64 and enable the support in BLAKE3.
=> Improve simd detection

LICENSE.adoc, src/TemporaryFile.cpp, src/third_party/CMakeLists.txt, src/third_party/win32/mktemp.c, src/third_party/win32/mktemp.h, unittest/CMakeLists.txt, unittest/test_bsdmkstemp.cpp
On Windows, multiple ccache process can race each other to create, rename and delete temporary files, because they would attempt to generate the same sequence of temporary file names (`tmp.cpp_stdout.iG2Kb7`, `tmp.cpp_stdout.P1kAlM`, `tmp.cpp_stdout.FzP5tM`, ...). I observed this behaviour in [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) when running a multithreaded build of a C++ project.
Root cause appears to be that the offical Windows ccache builds use mingw-w64's [implementation of `mkstemp()`][1], which uses `rand()` to generate temporary file names.
This PR replaces `mkstemp()` with a safer implementation that uses the CRT's `rand_s()` function to generate temporary file names that are more likely to be unique. `rand_s()` uses `RtlGenRandom()` …
=> Make TemporaryFile generate unique file names on Windows

misc/format-files, test/run, test/suites/base.bash, test/suites/cache_levels.bash
Bash tests were not actually being run on the macOS CI agents because the version of sed installed there does not understand the `-r` flag:
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
The PR:
- fixes scripts to use `sed -E` instead of `sed -r` as the latter isn't supported by BSD sed.
- exports `SDKROOT` in `test/run`. Otherwise it appears at least some some Apple toolchains (e.g. Xcode 10.3) will pick the _latest_ SDK installed on the host (e.g. `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk`) instead of using the SDK bundled with the toolchain (e.g. `/Applications/Xcode_10.3.app/.../MacOSX10.14.sdk`).
The 10.15 SDK is not compatible with Xcode 10.3:
ld: unsupported tapi …
=> Fix running tests on macOS

doc/MANUAL.adoc, src/ccache.cpp, test/suites/base.bash
SOURCE_DATE_EPOCH will be passed from debhelpers, by extracting last
entry from d/changelog (or current time if there is entries)
And this will not allow to use cache.
=> Ignore SOURCE_DATE_EPOCH under time_macros sloppiness

src/Logging.cpp
some 32bit architectures e.g. RISCV32 use 64bit time_t from beginning
which does not fit into long int size on LP32 systems
Upstream-Status: Pending
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> Always use 64bit to print time_t

.github/workflows/build.yaml
As randomly discovered in #751 the testdir.tar filenames contain `{{ matrix.config.version }}` which looks rather strange. A dollar sign was missing.
=> CI: Fix testdir upload file name in case of failed tests

src/Lockfile.cpp, unittest/test_Lockfile.cpp
Fix flipped condition test that meant the file lock wouldn't be acquired if parent directories needed to be created first.
I noticed this when looking at some of the Windows test failures, as stats files wouldn't be updated.
=> Fix Lockfile on Windows when parent directories do not exist

.github/workflows/codeql-analysis.yaml
While I'm not 100% sure this makes a lot of sense, I have it up and running so it makes sense to at least create a pull request.
The only downside I see so far is that it runs for ~7 minutes which makes it the slowest Actions Job we have. I'm not really sure this will ever catch anything since ccache is not really that user facing and security relevant. On the other hand these days everything is security relevant and it might be a low price to pay if this ever actually catches anything.
Background info: https://github.blog/2020-09-30-code-scanning-is-now-available/
=> Add CodeQL

doc/MANUAL.adoc
Soome locales like `LANG=fr_FR.iso885915@euro make` can't
handle UTF-8 single- and double-quotes:
```
$ LANG=fr_FR.iso885915@euro make
...
asciidoc: FAILED: MANUAL.adoc: line 529: unexpected error:
...
File "/usr/lib/python3.8/encodings/iso8859_15.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u201c'
in position 54: character maps to <undefined>
```
To avoid it the patch uses ASCII equivalents of symbols.
The patch is generated as:
```shell
$ sed \
-e 's/\xE2\x80\x99/'\''/g' \
-e 's/\xE2\x80\x9C/"/g' \
-e 's/\xE2\x80\x9D/"/g' \
-i doc/MANUAL.adoc
```
Reported-by: Christophe PEREZ
Bug: https://bugs.gentoo.org/762814
=> doc/MANUAL.adoc: don't use non-ASCII quotes

test/run, test/suites/base.bash, test/suites/cleanup.bash, test/suites/inode_cache.bash
Small tweaks to get more tests passing on Windows: account for `\r\n` line endings in `ccache --version` test, and skip some tests that can never succeed on Windows.
I noticed that having more tests running on Windows would increase CI test run times by a few minutes. This seems to be due to git-bash's emulation of fork/exec being extremely slow -- on my machine it's roughly 30ms to spawn `/usr/bin/true` from a bash script compared to 2ms on my macOS machine. So I've also made some tweaks to improve performance on Windows by avoiding unneeded subshells.
Also fixes some other issues with the test suite:
- having multiple arguments in `CC` wasn't handled properly in some cases
- on test failure we'd pass the test name directly to `printf`, which caused some confusing errors when the test …
=> Test suite fixes and improvements for Windows

.github/workflows/build.yaml, cmake/UseFastestLinker.cmake
Turns out it would have been a good idea to add that to CI in the first place.
Current master fails to compile if ld.gold / lld are installed with gcc <9.
=> Fix fast linker selection for old gcc versions

.github/workflows/build.yaml, test/run
Make `is_equal_object_files` more lenient when comparing COFF object files.
COFF object files contain the original source file name, which was breaking the cpp1 test. They often contain a timestamp used by the incremental linker, unless this is explicitly disabled via `/Brepro` (MSVC) or `-mno-incremental-linker-compatible` (clang).
=> Tests: improve COFF object file comparison

.github/workflows/build.yaml
The auto cleanup step that runs after `brew install` can can often add a few minutes to each macOS CI run.
=> CI: skip homebrew update/cleanup on macOS

CMakeLists.txt, cmake/GenerateConfigurationFile.cmake, cmake/config.h.in, src/system.hpp
The inode cache requires pthread_mutexattr_setpshared() and build fails on OS with sys/mman.h that do not have this function. Here's my attempt at checking for this in the CMake files and disabling the feature if needed.
=> disable inode cache on OS without pthread_mutexattr_setpshared()

cmake/StdAtomic.cmake
On sparc there are 8-byte atomic loads and stores available in ISA
but not atomic increments. As a result linking fails as:
```
ld: src/libccache_lib.a(InodeCache.cpp.o):
undefined reference to symbol '__atomic_fetch_add_8@@LIBATOMIC_1.0'
ld: sparc-unknown-linux-gnu/8.2.0/libatomic.so.1:
error adding symbols: DSO missing from command line
```
The fix is to add increment into libatomic test.
tested on `sparc-unknown-linux-gnu` target.
=> StdAtomic.cmake: probe atomic increment as well

src/argprocessing.cpp, test/suites/color_diagnostics.bash, unittest/test_argprocessing.cpp
Before this change `clang++ -Xclang -fcolor-diagnostics -c foo.cc`
would result in diagnostics without color if stderr was not a TTY.
Fixes #801.
=> Support -fcolor-diagnostics passed to cc1 with -Xclang

cmake/config.h.in, src/ccache.cpp, src/system.hpp, unittest/test_Util.cpp
- Update of config.h.in to build with xlclang++ on AIX72
- Little fixes in code chunks never built on usual platforms
=> Build ccache with xlclang++ on AIX72

src/Util.cpp, unittest/test_Util.cpp
If the size_hint passed to `Util::read_file()` was an underestimate, or the platform's `stat()` implementation gives an inaccurate file size (e.g. MinGW) then `Util::read_file()` would only issue a single `read()` call instead of reading the entire file.
Fixes #803.
=> Fix Util::read_file returning truncated results if size_hint is an underestimate

test/suites/base.bash
Trivial fix for 'debug option' test from base testsuite.
Previously `reference_test1.o` was compared to itself, therefore not really testing anything.
Now it properly compares `reference_test1.o` to `test1.o` to check that CCACHE produces the same output as real compiler.
=> Fix "Debug option" test

cmake/UseCcache.cmake
Ccache does not support cl.exe-style arguments at this time.
=> Build: don't enable ccache when building with MSVC

test/run
The line is printed with "Test suite:" as line numbers are counted relative to the start of that file, and to avoid adding another line to the output:
```
Running test suite base.
FAILED
Test suite:     base (line 11)
Test case:      Base case
Failure reason: Objects differ: reference_test1.o != test1.o
```
=> test: print line number of failing assert

src/Win32Util.cpp, src/Win32Util.hpp, src/ccache.cpp, src/execute.cpp, src/execute.hpp, src/system.hpp, unittest/test_Win32Util.cpp
I'm trying to make Ccache work (again) on Windows. What is broken: handling of "execute" with long command parameters (see win32execute).
In more details:
- parameter lpCommandLine was formatted incorrectly (it has to contain app name too)
- temporary file with parameters to the compiler was formatted incorrectly (it should NOT contain app name; if it contains backslashes, then these backslashes need to be escaped as double-backslashes)
- wrong location (directory) of temporary files in win32execute
- premature deletion of temporary files in win32execute
=> Fix win32execute

doc/INSTALL.md
It looks like https://zstd.net isn't working anymore, however, http://zstd.net works and simply redirects to https://facebook.github.io/zstd/ which is served through https.
This change essentially reverts a single change from commit a0f32f161f1b8b9c5d287ca8abe88e3fd1e940a2: where the `zstd` url was changed from `http` to `https`.
=> Changed zstd url back to http

.github/workflows/build.yaml, src/Stat.cpp, src/Win32Util.cpp, src/Win32Util.hpp, src/system.hpp, unittest/test_Stat.cpp
Win32 functions like `CreateFile` return `ERROR_ACCESS_DENIED` when a file is in the process of being deleted, which gets mapped to an errno of `EACCES`. For the purposes of `Stat::stat` and `Stat::lstat`, it's more useful to treat this as a missing file and map this to an errno of `ENOENT`.
Speculative fix for issue noted by @brechtsanders in https://github.com/ccache/ccache/issues/831#issuecomment-811029194
> [...]  I got an error building gstreamer 1.18.4 in one of my MinGW-w64 environments:
> ```
> ccache: error: failed to lstat D:\Prog\winlibs64-10.2.1\home/ccache/tmp/tmp.cpp_stdout.pBIXIw.i: Permission denied
> ```
Also: fix clang-tidy job following GitHub changing default clang version in their Ubuntu 18.04 runners. https://github.com/actions/virtual-environments/issues/2950
=> Stat: treat pending deletes as missing files on Windows 

cmake/GenerateConfigurationFile.cmake
Add the -pthread flag to the compiler when building the test
program. Otherwise the compiler will build with wrong defines.
Fixes failing unit tests in ubuntu 18.04.
=> Fix detection of pthread features

CMakeLists.txt
So we don't need to support corner cases as for example one fixed in
commit f6202db308e3 ("doc/MANUAL.adoc: Don't use non-ASCII quotes
(#761)") when the documentation is actually not needed at all as ccache
is used as a build tool only.
Signed-off-by: Petr Štetiar <ynezz@true.cz>
=> CMake: make build of documentation optional

src/ccache.cpp, src/compopt.cpp
This is more or less equivalent to gcc's --specs option except that the
contents of the file have different syntaxes.
=> Add support for clang's --config option

src/MiniTrace.cpp, src/MiniTrace.hpp, src/third_party/CMakeLists.txt
Need to make sure to pass the -DMTR_ENABLED also when compiling
the library and not only in the ccache internal config.h file.
Also the strings used need to be still around when the destructor
is called, so avoid using local strings and any strdup strings.
Closes #851
=> Enable minitrace tracing and stop it from crashing

doc/MANUAL.adoc, src/Config.cpp, src/Config.hpp, src/Statistics.cpp, src/Statistics.hpp, src/ccache.cpp, unittest/test_Config.cpp, unittest/test_Statistics.cpp
This is a reimplementation of the original feature, 4e2799df1d3b617525235fa43f8ab048397ddbae
It adds an optional stats log, that will log the input files and their results (only)
```
cache_miss
cache_miss
direct_cache_hit
direct_cache_hit
```
_all lines starting with `#` are regarded as comments, and ignored as results_
It also adds a new command `--log-stats`, that will parse and present this file.
```
cache hit (direct)                     2
cache hit (preprocessed)               0
cache miss                             2
cache hit rate                     50.00 %
```
Closes #262
=> Add stats log file, logging input file and result

test/suites/modules.bash
Typically, clang is able to auto-detect C++ files and switch to C++
mode, even when `argv[0]` is simply `clang` (without the `++`).
However, Nixpkgs provides `clang` as a wrapper script over the
underlying compiler binary, and only enables C++ standard library
include paths when it thinks it's being invoked as a C++ compiler:
https://github.com/NixOS/nixpkgs/blob/961cae37edeb34b5dec8060e49e5abbde3af9c00/pkgs/build-support/cc-wrapper/cc-wrapper.sh#L28
https://github.com/NixOS/nixpkgs/blob/961cae37edeb34b5dec8060e49e5abbde3af9c00/pkgs/build-support/cc-wrapper/cc-wrapper.sh#L54-L55
https://github.com/NixOS/nixpkgs/blob/961cae37edeb34b5dec8060e49e5abbde3af9c00/pkgs/build-support/cc-wrapper/cc-wrapper.sh#L135-L138
So for the benefit of less clever compiler toolchains which
can't always see …
=> Explicitly select C++ when using -fcxx-modules

test/suites/nvcc_ldir.bash
Add detection to nvcc_ldir of whether nvcc works with chosen host
compiler. For instance, nvcc aborts with
#error -- unsupported clang version! clang version must be less than 9 and greater than 3.2
if the version of clang (or gcc) is too new. The test should be skipped in
this case.
=> Skip nvcc_ldir test with non-working nvcc.

test/suites/ivfsoverlay.bash
Add CCACHE_SLOPPINESS=include_file_mtime to ivfsoverlay test. This is
possibly due to me using my self-compiled clang since it does not fail
with the version of Clang that comes with Ubuntu 20.04.
=> Add sloppy include_file_mtime to ivfsoverlay test

cmake/StandardSettings.cmake
According to
https://cmake.org/cmake/help/latest/command/target_compile_options.html,
compile options are de-duplicated individually, presumably leading to
any non-first "/FI" to be removed. Put flag and option into quotes to interpret as a
single option.
Observed with CMake 3.20.3. I don't know why this does not happen with
-include or what the first /FI option could be.
=> Put compile option with args into quotes

test/run, test/suites/direct_gcc.bash
Apple Clang, when called via `gcc`, emits a `Configured with` line
on stderr which confuses the compiler detection. As a consequence
lots of tests were skipped.
To work-around default to clang on macOS.
=> fix: AppleClang detection

test/CMakeLists.txt
With multi-config generators like Xcode the binary is stored within an extra Debug / Release directory.
Tested with CMake 3.4.3
=> Use generator expression for ccache location

doc/MANUAL.adoc, src/Manifest.cpp, src/Result.cpp
Similar to other commands, such as tar
Useful when streaming data, for instance:
```console
$ redis-cli get "ccache:b3c3hb1g03rej3p4o4qqm2bkiq3ch47cs" | ./build/ccache --dump-manifest -
Magic: cCmF
Version: 2
Compression type: zstd
Compression level: 1
Content size: 31187
...
$ redis-cli get "ccache:472amgcrp0t7dubsit1mua2lc849lr81q" | ./build/ccache --dump-result -
Magic: cCrS
Version: 1
Compression type: zstd
Compression level: 1
Content size: 1186630
...
```
=> Allow dumping stdin by giving - as path

misc/ccache.magic
Useful when working with streams from server
```console
$ redis-cli get "ccache:b3c3hb1g03rej3p4o4qqm2bkiq3ch47cs" | file -
/dev/stdin: ccache manifest, version 2
$ redis-cli get "ccache:472amgcrp0t7dubsit1mua2lc849lr81q" | file -
/dev/stdin: ccache result, version 1
```
Installed in regular locations for the `file`  command.
<http://darwinsys.com/file/>
=> Add magic file, for identifying ccache files

CMakeLists.txt, cmake/GenerateConfigurationFile.cmake
When enabling CMake policy [CMP0067](https://cmake.org/cmake/help/latest/policy/CMP0067.html) by either enabling it directly or via a `cmake_minimum_required` of `3.8` or later, the `test.inode_cache` test starts to fail.
This happens because this policy slightly changes the `CheckCSourceCompiles` logic by passing-in any configured C-standard. The detection of the following features now report absence:
```diff
--- CMakeCache-old.txt	2021-07-05 15:50:25.698278961 +0200
+++ CMakeCache-new.txt	2021-07-05 15:50:54.626397301 +0200
@@ -657,7 +657,7 @@
//Have function pthread_mutexattr_setpshared
HAVE_PTHREAD_MUTEXATTR_SETPSHARED:INTERNAL=1
//Test HAVE_PTHREAD_MUTEX_ROBUST
-HAVE_PTHREAD_MUTEX_ROBUST:INTERNAL=1
+HAVE_PTHREAD_MUTEX_ROBUST:INTERNAL=
//Have include pwd.h
HAVE_PWD_H:INTERNAL=1
//Have …
```
=> Fix CMake feature detection

src/ccache.cpp
I added this in 3ec58dbcaa1e7903d59dce4c77baff7bc3783269 as I thought clang only saves the timestamps of included files, so as long as they are turned off by -Xclang -fno-pch-timestamp, preprocessed hits should be possible. However, clang also saves the size and possibly a hash of the un-preprocessed source file, so preprocessed hits don't make much sense.
As long as only the timestamp of a PCH source file changed, e.g. through git operations, there should still be direct hits (as long as -Xclang -fno-pch-timestamp is used).
=>  Disable preprocessor hits for PCHs with clang again

doc/MANUAL.adoc, doc/NEWS.adoc
asciidoc uses #_section_header, but github uses #section-header.
Replace all the explicit refs with the section titles, and let
the engine handle it.
=> docs: Fix links to section anchors

doc/MANUAL.adoc, src/storage/Storage.cpp, src/storage/secondary/SecondaryStorage.cpp, test/suites/secondary_file.bash
This adds support for a shards attribute with a comma-separated list of names for sharding (partitioning) the cache entries using Rendezvous hashing, typically to spread the cache over a server cluster. When set, the storage URL must contain an asterisk (`*`), which will be replaced by one of the shard names to form a real URL. A shard name can optionally have an appended weight within parentheses to indicate how much of the key space should be associated with that shard. A shard with weight **w** will contain **w/S** of the cache, where **S** is the sum of all shard weights. A weight could for instance be set to represent the available memory for a memory cache on a specific server. The default weight is **1**.
For example,
redis://cache-*.example.com|shards=a(3),b(1),c(1.5)
will put 55% …
=> Add support for cache sharding on secondary storage

src/CMakeLists.txt, src/third_party/CMakeLists.txt
The library ws2_32 is used in third_party, but linked against ccache_framework. 
This has the consequence that the symbols cannot be resolved when building with gcc:
```
.../ld.exe: src/third_party/libthird_party.a(httplib.cpp.obj): in function `httplib::detail::close_socket(unsigned long long)':
ccache/src/third_party/httplib.cpp:371: undefined reference to `__imp_closesocket'
.../ld.exe: src/third_party/libthird_party.a(httplib.cpp.obj):ccache/src/third_party/httplib.cpp:410: undefined reference to `__imp_select'
.../ld.exe: src/third_party/libthird_party.a(httplib.cpp.obj):ccache/src/third_party/httplib.cpp:438: undefined reference to `__imp_select'
.../ld.exe: src/third_party/libthird_party.a(httplib.cpp.obj):ccache/src/third_party/httplib.cpp:478: undefined reference to …
```
=> build: Link ws2_32 to third_party instead of ccache_framework

test/run, test/suites/secondary_file.bash
I got a strange `find: illegal option -- t` error due to `$dir` evaluating to nothing.
=> fix(test): Pass all three required arguments to expect_file_count

src/storage/secondary/HttpStorage.cpp
If compilation takes very long and the remote end closes
the http connection between the GETs and the PUTs the
ccache process dies with a SIGPIPE. Better disable keep-alive
handling until httplib is fixed.
=> fix(http-storage): Disable broken connection keep-alive

test/suites/basedir.bash
`/bin/pwd` won't exist on some systems (eg. NixOS). The only difference between the shell builtin and the binary is that the binary uses `-P` by default. By passing `-P` we can be sure that we get the actual path, and not the symlinked path, which was needed for #916.
=> Use shell builtin pwd for basedir test

src/ccache.cpp, src/util/path.cpp, src/util/path.hpp, unittest/test_util_path.cpp
The drive letter removal was incorrect.
=> fix: Correct debug dir handling on Windows

misc/codespell-allowlist.txt, src/Args.cpp, src/Args.hpp, src/Config.cpp, src/Config.hpp, src/argprocessing.cpp, src/ccache.cpp, src/compopt.cpp, unittest/test_Args.cpp
I picked only the compiler commits from: https://github.com/ccache/ccache/pull/162
The following commits I've adapted to the latest ccache C++ code:
375fe24: Add compiler_is_msvc() and MSVC specific option table.
7e01763: Add handling of /Fo option (replaces -o, but shall have no
space)
0c5cd25: Manage /E, /c equivalence. -g is gcc only. -O or /O is msvc
only.
4f61b59: MSVC send part of the error/warning messages to STDOUT, so
concat wit…
64449d6: use common code for gcc an cl response files.
I have tested this with CMake using the Ninja generator in Release mode. It seems to work good enough for having it in GitHub actions for [Qt Creator](https://github.com/qt-creator/qt-creator/actions).
Fixes: https://github.com/ccache/ccache/issues/431
=> Visual C/C++ compiler support

cmake/GenerateConfigurationFile.cmake, src/hashutil.cpp
With GCC it's necessary to explicitly enable AVX2, otherwise GCC will complain about use of AVX2 intrinsics. But MSVC does not require any enabling, it's enough to write the intrinsics.
=> fix: Make AVX2 code work also with MSVC

src/argprocessing.cpp
This is separated out from #954 , as this one is rather simple.
=> fix: Use default object file extension .obj for MSVC

src/Util.cpp, src/Util.hpp
Fix newline handling of `send_to_stderr` on Windows.
This bugfix is a precondition for the feature in #962.
=> fix: handle newlines on Windows properly

doc/MANUAL.adoc, src/ccache.cpp
There does not appear to be any way to disable preprocessing with
MSVC. And invoking it with .ii file will result in warnings about
file type not being recognized and no action being performed.
=> fix: Ignore CCACHE_NOCPP2=1 with MSVC

src/argprocessing.cpp, src/compopt.cpp
These are various fixes (on top) of #506 .
=> Fix and simplify handling of options for MSVC

src/argprocessing.cpp, src/compopt.cpp
=> fix: Handle MSVC flags -MD[d], -MT[d] and -LT[d] properly

src/compopt.cpp
Everything after it should be passed to the linker, which conflicts
with ccache appending its extra arguments when calling the compiler.
This probably could be handled somehow, but ccache shouldn't cache
compilations that also link, so either the option doesn't belong
there anyway, or the compilation cannot be cached.
=> MSVC's -link option is too hard

src/Util.cpp, test/suites/secondary_file.bash, unittest/test_Util.cpp
The Secondary Storage creates corrupted files when they are copied to the Primary Storage.
The flag `O_BINARY` fix that issue.
=> Fix copying of binary files on Windows

src/ccache.cpp, test/suites/base.bash
With this patch accepts C++ code like `obj.incbin(x)`.
Previously it complained `Found unsupported .incbin directive`.
Fixes: #982
=> fix: avoid .incbin false positive

src/argprocessing.cpp, src/compopt.cpp
This more or less maps to PCH support for GCC/Clang, just handle
the /Yu and /Fp options.
Note that MSVC is apparently unable to generate the same PCH
from the same sources, just like GCC, so a rebuild that also rebuilds
the PCH will get cache misses. So either somebody can add support
for -Yc (if caching those huge PCHs is a good idea), or
CCACHE_PCH_EXTSUM can be used (with a checksum based on preprocessed
PCH input, i.e. -E instead of -c -Yc).
=> support MSVC /Yu option (compiling with PCH)

misc/upload-redis
There were some assertions in the file upload, that didn't match the new file format.
Updated the helper script to work with both versions, so that it would match either...
=> Fix upload-redis after cache entry format change

src/argprocessing.cpp
While MSVC technically has that option as deprecated, it's a source
of trouble with the way ccache curently handles the option, and since
it broke ccache's debug output, it was hard to find.
=> do not handle -o<file> for MSVC

doc/MANUAL.adoc, src/storage/secondary/HttpStorage.cpp
The issue that made us not enable HTTP keep-alive by default (yhirose/cpp-httplib#1041) was resolved in cpp-httplib 0.10.0 (upgraded in e22e934dcaf1).
@gjasny: Does this sound OK to you?
=> feat: Enable HTTP keep-alive by default

doc/MANUAL.adoc, src/storage/secondary/HttpStorage.cpp
This a proposal to add support for Bearer Authorization to the HTTP secondary storage backend.
I tested it locally and it worked perfectly: files were uploaded on GCloud during first build, and second build was much faster (after cleaning the cache).
Let me know if you prefer a different name than `"bearer-token"` or for any other improvement. Maybe we should redact the token in the logs (I don't know if it's logged) as it is done for the password?
Fixes #997.
=> feat: Add option to use Bearer token with HTTP backend

src/Config.cpp, src/Config.hpp, src/argprocessing.cpp, src/ccache.cpp
Without this, clang-cl is detected as clang and then ccache barfs
because clang-cl produces stdout output.
=> Detect clang-cl as a compiler

src/Config.cpp
Amends 32c708525f80db08e6399628cdb944a67e4eba69
=> Fix clang-cl display name

doc/MANUAL.adoc
I've been bisecting the Linux kernel for a few days now, and had a hard time figuring out why ccache had a hit rate around 3% even though I've been recompiling the same code over and over again - until I learned about the existence of compiler plugins today. As the kernel's GCC plugins are rebuilt after every `make clean`, this kept triggering the compilercheck on every build, even though the compiler itself never changed (of course). Therefore adding a hint at the compilercheck documentation for future-me that plugins are considered in this check too.
=> Add documentation that compiler plugins are hashed too

src/Args.cpp, src/Util.cpp, src/Util.hpp, unittest/test_Util.cpp
Visual Studio writes its .rsp files with UTF-16 encoding
which need to be converted to UTF-8 so that ccache
can be used within Visual Studio
=> fix: Support UTF-16LE .rsp files

src/Util.cpp, src/Util.hpp, src/argprocessing.cpp, src/util/path.cpp, src/util/path.hpp, unittest/test_Util.cpp, unittest/test_util_path.cpp
When testing `ccache` in my projects using MSVC via cmake and ninja I found that the relative path handling triggered via the "base_dir" config option would not work for all compiler invokations generated by CMake.
This is especially critical as some CIs like e.g. drone use unique build directories and as such caching depends on paths to be always relative.
This PR addresses the two issues I found in the code which prevented base paths to be properly generated in my setup.
=> fix: Make conversion to relative paths more reliable on Windows

src/storage/secondary/RedisStorage.cpp
Redis servers configured with authentication require successful authentication before database selection.
Fix bug that can only occur when attempting to use a non-zero database on a Redis server that requires authentication.
When connecting to a Redis server a client operates against database 0 by default.
The select_database function returns early without performing an action on the Redis server if the database in the URL variable is explicitly set to zero, or is not specified and therefore assumed to be database 0.
When the url contains a database of 1 or higher a redis transaction to select the requested database is performed, this transaction will fail if the Redis server requires authentication and authentication has not been performed.
=> Authenticate Redis before database selection

src/ccache.cpp
A potential fix for ccache errors that terminate builds with:
ccache: error: Failed to read from file stream
This error happens sporadically when compiling and is hard to pin down
for reproduction.
It looks like this is caused by a code path missing a catch for the
core::Error exception that can happen when the fread returns zero bytes
in FileReader::read()
By code inspection the most probable place this could happen is in the
constructor of CacheEntryReader which consumes a Reader and performs
reads without exception handling around all of the reads.
Extend the try catch around the creation of the cache_entry_reader object
in the from_cache function to protect this code path.
There is potential for this error to also happen in inspect_path and
in the EXTRACT_RESULT case of …
=> Fix ccache: error: Failed to read from file stream

CMakeLists.txt
ccache is providing a `Findzstd.cmake CMake` find module, which is
ignored when `CMAKE_FIND_PACKAGE_PREFER_CONFIG` is set to `ON`.
=> fix: Prefer CMake find module for zstd package

doc/INSTALL.md
Adding a reference to GH workflows as source of build setup information
Side effect of #1009
=> docs: Add reference to reference build configs

CMakeLists.txt
This fixes building and linking blake3 with MSVC for both Ninja and
msbuild.
See #1009.
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
=> fix: Add ASM and ASM_MASM to project() languages

src/Util.cpp, src/Util.hpp, src/ccache.cpp, src/util/Tokenizer.cpp, src/util/Tokenizer.hpp, unittest/test_util_Tokenizer.cpp
Tokenizer is used with `include_empty`, and the output typically ends with `\n`.
For each line, tokenizer returns it without the `\n`, and the function appends it. But if the output ends with `\n`, the tokenizer returns an additional empty string, and a redundant `LF` is written to stdout.
Another issue can be if the last line of the original output doesn't end with `\n` at all, ccache added it anyway.
It was probably unnoticed until now since gcc has no output at all, while cl outputs the source file name.
=> fix: Do not add redundant newlines for stdout

src/Depfile.cpp, src/Util.cpp, src/util/Tokenizer.cpp, src/util/Tokenizer.hpp, unittest/test_util_Tokenizer.cpp
It is more accurate, in case the original output doesn't end with \n.
=> fix: Replace skip_last_empty with IncludeDelimiter

src/ArgsInfo.hpp, src/argprocessing.cpp, src/ccache.cpp
On windows with basedir to set e.g. C:\Projects, it will
get normalized to C:/Projects. With a header in C:\Projects\repo\some_header.h,
during include reading it may be read as C:\\\\\\\\Projects\\\\\\\\\repo\\\\\\\\some_header.h
with additional slashes. It does not then match basedir and is not changed to
relative when it should be.
Also the header paths printed to stdout need to be changed to relative so that Ninja will
use the relative paths to headers to detect changes instead of absolute paths. Otherwise
Ninja will check for header changes from the original build dir if an object was restored
from cache to another build dir.
=> fix: normalize abs paths when collecting includes to fix basedir option

test/suites/profiling.bash
Fixes two unrelated causes of sporatic failures in profiling tests.
1. Using `cut`, which is always line-based, to remove bytes from a binary file can cause problems if the binary timestamp field happens to contain a newline character, which causes `test.profiling` to fail <1% of the time.  Instead use `tail` which has a character mode that ignores newlines.
~~2. Sometimes ccache.log contains `test.c too new` so copy the format of `SETUP` in `direct.bash` to `profiling*.bash`.~~
=> Fix sporatic test.profiling failures

cmake/StandardSettings.cmake
Avoids passing `-include` to `clang-cl` which is not a valid argument.
=> build: Fix build arguments to clang-cl

misc/upload-redis
Originally it was written more as a debugging helper,
but can come in handy for uploading primary to secondary.
Make the output more usable, with a progress bar and a
size summary. And do MPUT pipelining, which is 5x faster.
----
Other tools, like `ccache -c` or `ccache -x`.
=> Make the `upload-redis` output more like other tools

src/argprocessing.cpp
When using ccache on Windows with MSVC with precompiled headers sometimes the following error occures: "Multiple precompiled headers used: precompiled_header.pch and precompiled_header.pch".  This happens if you specify /Fp before /Yu. I fixed it in the same manner as /Fp handles being after /Yu but not sure if it's the best approach.
=> Fix "Multiple precompiled headers used" error if /Yu option is used after /Fp

src/core/Reader.hpp
The `read_int` function checks for short reads so `read_str` should do as well.
Additionally don't trigger undefined behavior with `operator[]` on empty strings.
=> fix: Check for short reads in Reader::read_str

src/third_party/nonstd/expected.hpp
=> fix: Fix miscompile of nonstd::expected on MSVC v19.22

src/Args.cpp, src/Args.hpp, src/argprocessing.cpp, unittest/test_Args.cpp
Inside response files passed to clang-cl or msvc:
1. `\` should not be ignored completely, but rather it should only escape `\` and `"`.
2. `'` should not be treated specially.
=> fix: Fix parsing of MSVC response files

src/ccache.cpp
=> fix: Skip empty files names in preprocessor output

misc/upload-redis
Accidentally introduced a bug, when moving to use pipelines and refactoring:
* #1070
After reading the files and preparing the set, it was not actually commited to server.
Fixed, and now also uploading in smaller batches and only if value does not exist...
=> Redis upload bugfix and further optimization

src/execute.cpp
Putting all arguments in quotes is done in `argv_to_string`, however when ccache uses `cmd_args` response file, `argv[0]` ends up being without quotes which ends up badly if it has spaces in it. In my case it resulted in preprocessor error and subsequent cache misses.
=> fix(win32execute): Handle space in paths when using response file

CMakeLists.txt, src/CMakeLists.txt
Set cmake to prefer static libraries in general when enabled, defaulting
to ON for Win32.
Hide the gory details in cmake/StaticLink.cmake.
If not using internet versions, try to find static versions of zstd and
hiredis and set the IMPORTED_LOCATION property accordingly. This links
the MSYS2 versions of zstd and hiredis statically correctly.
On MSVC rewrite /MD[d] to /MT[d] to link the runtime statically.
On MINGW add -static-gcc and -static-libstdc++ to link flags and static
libwinpthread to libs.
On Win32 Clang add static libc++ and libunwind to libs.
On Win32 also add the psapi and ws2_32 standard dlls, needed by static
versions of some libs.
All of this is stemming from the discussion in #1009, where the core
issue still needs investigation.
Signed-off-by: Rafael Kitover …
=> feat: Generalize STATIC_LINK option + fixes

src/ccache.cpp, src/storage/Storage.cpp, src/storage/Storage.hpp
On a manifest key miss in the primary cache the manifest from secondary
storage is fetched. This will incrementally update secondary storage
cache manifest files instead of overwriting them with modified primary
storage manifests. Which in turn makes direct hits being properly shared
between machines through secondary storage.
Partially resolves issue described in #1049
=> feat: Fetch/update secondary storage manifest on primary miss

src/core/exceptions.hpp
So this is the simplest fix I came up with, if we specify the first argument to be exactly of type `const char *` then we definitely cannot intersect with special member functions.
The only downside is probably inability to use compile time argument checking with `FMT_STRING` but since it is not done currently I think it should not be a problem.
I understand that it may seem like a workaround but in reality this construct is fragile and could become broken for other compiler as I demonstrate here with adding `catch` (thanks to Jonathan Caves from Microsoft for pointing this out) https://gcc.godbolt.org/z/qG1rjPMsr 
Fixes #1076
=> build: Fix build with newer MSVC 2022 versions

misc/download-redis
Normally one would have the primary cache around still,
but sometimes it can be useful to download from secondary.
The Redis symantics between `KEYS` and `SCAN` are confusing*,
so add a small helper script to avoid accidents if attempting...
----
\* using KEYS on a redis server downloads _all_ the keys at once,
bringing down the server. using SCAN downloads 10 at a time.
Unfortunately SSDB uses a different syntax, for keys and scan.
So it is currently **not** compatible, before fixing [redis-py](https://pypi.org/project/redis/) to match.
=> Add download-redis script matching the upload-redis

CMakeLists.txt, cmake/Findhiredis.cmake, cmake/Findzstd.cmake, src/CMakeLists.txt
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
This is the auto `FROM_INTERNET` thing I promised to do.
This is almost completely backwards compatible, except the behavior of the `FROM_INTERNET` cmake options is slightly different, they are `ON` by default, and if the user did not enable `STATIC_LINK` and a system library is available, it will be linked shared.
Also a loud warning is printed when a dep is used `FROM_INTERNET`.
Still smoothing out some minor details, so this PR is a draft.
=> feat: auto dep FROM_INTERNET when unavailable

src/core/mainoptions.cpp
It currently prints "clang.exe version x.y.z"
=> fix: Strip .exe from executable name on version output

src/Config.hpp, src/core/Statistics.hpp
The build issues are seen with musl + gcc12, the issues are latent with glibc which is indirectly including these headers
=> Fix build with musl when using gcc12

.github/workflows/build.yaml, .github/workflows/codeql-analysis.yaml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows. 
GitHub Actions workflows have a GITHUB_TOKEN with `write` access to multiple scopes. 
Here is an example of the permissions in one of the workflows:
https://github.com/ccache/ccache/actions/runs/3046687499/jobs/4909809113#step:1:19
After this change, the scopes will be reduced to the minimum needed for each workflow. 
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced. 
- GitHub recommends defining minimum GITHUB_TOKEN permissions. 
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-githu …
=> ci: Add minimum GitHub token permissions for workflows

test/run
Missing space inside bash condition
Without this fix, there is an error returned when executing the run script with the option to keep the test directory `KEEP_TESTDIR`:
./run: line 645: [: missing `]'
=> fix: small typo in the run script

src/compopt.cpp
This should fix the issue as described in https://github.com/ccache/ccache/issues/1048 this has been tested with the repro steps and its found that the include ordering is correct with respect to each other.
=> feat: add support for -external:I for msvc

doc/MANUAL.adoc, src/Config.cpp, src/ccache.cpp, src/core/Sloppiness.hpp
This allows the use different -frandom-seed
values without causing cache misses.
Should fix https://github.com/ccache/ccache/issues/1002
=> feat: Add sloppiness for -frandom-seed

src/Util.cpp
`putenv("FOO")` doesn't really unset it. `putnev("FOO=")` sets an empty value, which might be good for most cases, but for really unsetting we need `SetEnvironmentVariable("FOO", NULL)`.
=> fix: Fix implementation of unsetenv on Windows

src/Util.cpp, src/ccache.cpp
When VS_UNICODE_OUTPUT is set, CL sends its (unicode) output to VS using a side-channel. This prevents the option to capture the output.
Unset this variable to enable capturing the output.
=> fix: Capture MSVC stdout/stderr when running from Visual Studio

cmake/Findzstd.cmake
pkgconfig is a more reliable way to search for libzstd, especially when not built with the non default cmake build.
Signed-off-by: Rosen Penev <rosenp@gmail.com>
=> build: Use pkgconfig for zstd search

src/ArgsInfo.hpp, src/Config.cpp, src/Config.hpp, src/Context.hpp, src/argprocessing.cpp, src/ccache.cpp, src/core/CMakeLists.txt, src/core/ResultRetriever.cpp, src/core/ShowIncludesParser.cpp, src/core/ShowIncludesParser.hpp, unittest/test_Config.cpp
If MSVC is executed *without* /showIncludes, and ccache is configured with depend mode, add /showIncludes, and strip the extra output from stdout.
=> feat: Support auto depend mode for MSVC without /showIncludes

src/ccache.cpp
When the cached data is read, the output to fd is binary (Util::send_to_fd), so in order to maintain the original line endings, the output must be stored as binary too.
=> fix: Store output without line-ending conversion

src/Depfile.cpp, unittest/test_Depfile.cpp
Support dependency files that are generated with spaces between the target and the colon sign.  This is the case for the tasking compiler but since this is supported by definition of the target, it could be generated theoretically by any compiler
=> fix: spaces between target and colon in dependency files

.github/workflows/build.yaml
It frequently fails to install packages.
=> build: Remove clang64 msys target from ci

src/CMakeLists.txt, src/core/CMakeLists.txt, src/storage/CMakeLists.txt, src/storage/local/CMakeLists.txt, src/storage/remote/CMakeLists.txt, src/third_party/CMakeLists.txt, src/third_party/blake3/CMakeLists.txt, src/util/CMakeLists.txt, unittest/CMakeLists.txt
Useful for listing them in the IDE project tree, for IDEs that use CMake file api (like Qt Creator).
=> build: Add headers to CMake project files

.github/workflows/build.yaml
It is deprecated.
See https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
Add GCC 12 on Ubuntu 22.04.
=> build: Remove Ubuntu 18.04 image from ci

cmake/StandardSettings.cmake, cmake/StdFilesystem.cmake
See https://discourse.cmake.org/t/correct-way-to-link-std-filesystem-with-gcc-8/4121
=> build: Fix compilation with GCC 8

cmake/StdAtomic.cmake
The required C++ is 17 anyway.
=> build: Remove unneeded C++11 flag in libatomic test

src/CMakeLists.txt
This ensures the required include of `config.h` to get `mode_t` defined on Windows.
=> build: apply standard settings and warnings to lockfile test

src/argprocessing.cpp, test/suites/multi_arch.bash
Since there are already checks enforcing that all -Xarch arguments match each other and -arch, we can assume that the compiler would also interpret the following argument, so ccache should interpret it too.
Fixes #1198.
=> fix: Process the argument following a -Xarch argument

src/hashutil.cpp, unittest/test_hashutil.cpp
If a non-temporal identifier, that ends with a temporal macro, happens to be at the end of the buffer with the temporal suffix starting on the avx boundary, then it would be incorrectly classified as a temporal macro. This since the helper function lacks the context to see that the data before the match is something that invalidates the match.
=> fix: Fix edge case where a non-temporal identifier is misidentified

src/Args.cpp, unittest/test_Args.cpp
Fixes #1216 , I tested the repro example provided and it should in fact compile. As such it seems that escaping backslashes is wrong all the other bug reports related to rsp parsing seems to only indicate issues with `"` whose escape behaviour remains.
Original fix #1071 did not indicate as to why backslashes should be escaped. As such I think its appropriate to revert that behaviour.
=> args: do not escape backslashes on msvc

src/InodeCache.cpp, src/InodeCache.hpp, test/suites/inode_cache.bash, unittest/test_InodeCache.cpp
These changes makes InodeCache working on FreeBSD (corresponging FSs were added to the list of supported filesystems).
Inode cache tests passes now on BSD and building a few large projects doesn't produces anything strange (inode cache file was created and updated during build).
=> fix: Use spinlocks for inodes cache buckets protection

cmake/DevModeWarnings.cmake, cmake/StandardSettings.cmake, unittest/CMakeLists.txt
This makes ccache build out of the box with clang-cl on Windows. I haven't done any benchmarks yet since I couldn't find any benchmarking tests in the source that executes on Windows so I don't know if it improves things. But usually clang-cl + LTO is faster than MSVC on Windows.
=> Make ccache compile with clang-cl on Windows

src/argprocessing.cpp, unittest/test_argprocessing.cpp
For MSVC /Zi is unsupported since it writes a additional
.pdb file per each .obj file and it creates some messy
interaction with ccache. But for clang-cl /Zi is actually
treated as /Z7 and only embeds the debug info in the .obj
file so it makes sense to allow this flag when compiling
with clang-cl.
=> Don't treat /Zi as unsupported for clang-cl.

src/argprocessing.cpp
=> fix: exclude /Zc flags from MSVC debug parameter (/Z) detection

test/suites/base.bash
Fixes: ef634bdb292e1e24b8d1b5490e7857144a77c0fd
=> test: Fix typo (missing line continuation)

.github/workflows/build.yaml, CMakeSettings.json, LICENSE.adoc, cmake/Findhiredis.cmake, cmake/Findzstd.cmake, src/third_party/blake3/CMakeLists.txt, src/third_party/blake3/blake3.c, src/third_party/blake3/blake3.h, src/third_party/blake3/blake3_avx2_x86-64_windows_gnu.S, src/third_party/blake3/blake3_avx512.c, src/third_party/blake3/blake3_avx512_x86-64_windows_gnu.S, src/third_party/blake3/blake3_dispatch.c, src/third_party/blake3/blake3_impl.h, src/third_party/blake3/blake3_sse2_x86-64_windows_gnu.S, src/third_party/blake3/blake3_sse41_x86-64_windows_gnu.S
- Fix the MSBuild CI jobs #1278 
- Update blake3 from 1.3.1 to 71a2646
- Fix cmake dev warning when downloading zstd/hiredis
- Add a basic CMakeSettings.json for Visual Studio IDE with Ninja as the generator
=> Fix MSBuild CI jobs + minor cmake fixes

src/ccache.cpp
The bug is introduced in commit 3ec0d4ec961cb0c67ff1603b83a6026d9f3abbb5.
=> fix: Keep the order of MSVC showIncludes output

cmake/Findzstd.cmake
Reproducer (CMake `3.26.4`, Xcode `14.3`):
```
cmake -B _build -GXcode -DCMAKE_OSX_ARCHITECTURES=x86_64 -DZSTD_FROM_INTERNET=ON -DREDIS_STORAGE_BACKEND=OFF
cmake --build _build
```
See facebook/zstd#3622
=> build: fix Xcode build of zstd

src/argprocessing.cpp
/Fd is to specify the file name of output PDB. But currently ccache only supports /Z7 which doesn't generate PDB at compile time.
/FS forces writes to PDB to be serialized through MSPDBSRV.EXE. It shouldn't affect generated files and it has no effect for /Z7.
/MP enables /FS. It creates multiple compiler instances and simultaneously compile multiple source files which is not supported by ccache.
- `/Fd`: https://learn.microsoft.com/en-us/cpp/build/reference/fd-program-database-file-name
- `/FS`: https://learn.microsoft.com/en-us/cpp/build/reference/fs-force-synchronous-pdb-writes
- `/MP`: https://learn.microsoft.com/en-us/cpp/build/reference/mp-build-with-multiple-processes
CMake adds `/Fd` and `/FS` unconditionally to compile options even though they only have effects with `/Zi` or …
=> feat: Don't hash /Fd, /FS and /MP

src/Args.cpp, unittest/test_Args.cpp
Parse correctly backslash escaped by backslash as in `/Fo"Dir\Dir\\"`.
The flag in the unit test `/Fo"N.dir\Release\\"` is taken from .rsp from VS22 project build. VS22 solution was generated by cmake 3.26.4. I'm not sure what is driving the use of the trailing backslash in the path used in `/Fo` flag, but these cases are definitely occurring in the wild for us.
I wasn't able to find spec for this case, but these rsp files with these escapes are correctly handled by CL. It makes sense that backslash can escape backslash, because otherwise it would not be possible to have backslash before `"` as the trailing backslash would otherwise escape `"`.
Cheers,
Jiri
[![image](https://user-images.githubusercontent.com/44769714/83034194-45548080-a038-11ea-9960-de502a30d89d.png)](http://www.ptc.com/) …
=> fix: Improve handling of backslash in MSVC .rsp

src/compopt.cpp, unittest/test_argprocessing.cpp
This PR addresses a bug that was uncovered while trying to enable `Werror` for both nvcc and the host compiler:
```bash
ccache nvcc -Werror all-warnings -Xcompiler -Werror -c foo.cu
```
```text
...
[2023-06-19T10:25:56.473230 5474 ] Command line: ccache nvcc -Werror all-warnings -Xcompiler -Werror -c foo.cu
[2023-06-19T10:25:56.473259 5474 ] Hostname: scrubbed
[2023-06-19T10:25:56.473270 5474 ] Working directory: /tmp
[2023-06-19T10:25:56.473281 5474 ] Compiler type: nvcc
[2023-06-19T10:25:56.473374 5474 ] No -c option found
[2023-06-19T10:25:56.473401 5474 ] Failed; falling back to running the real compiler
...
```
The primary change was defining `-Xcompiler/--compiler-options` as flags that take arguments. Modifications or changes are welcome - I'm by no means an expert with this …
=> fix: How nvcc handles host warnings by adding Xcompiler and --Werror.

src/Config.cpp, unittest/test_Config.cpp
Config directives such as cache_dir expand environment variables in their values ; debug_dir does not.
This is actually useful for me as I have  a ccache config I distribute to developers , I use their home directory for some ccache directory configs but could not do it for debug_dir.
=> feat: Expand  environment variables in debug_dir configuration entry

src/ArgsInfo.hpp, src/argprocessing.cpp, src/ccache.cpp, test/suites/multi_arch.bash
This pull request should bring more flexibility to iOS build caching. I admit that I am by far not a compiler expert so I did a lot of assumptions and I am opening this PR to get feedback.
The current situation is that multiple `-Xarch_*` arguments are not supported. Based on #874 I took a step forward and now match `-Xarch_*` to `-arch` and if they match, treat them as `-arch` arguments so adding them together to the each preprocessor run.
This allows me to efficiently cache multiarch iOS builds but I did not runtime test it yet if the output actually makes sense (the compilation finishes fine).
=> feat: Support multiple -Xarch_* arguments matching -arch

doc/MANUAL.adoc, src/Config.cpp, src/Config.hpp, src/ccache.cpp, unittest/test_Config.cpp
... via debug_level option or CCACHE_DEBUGLEVEL env variable.
With debug_level=2 (default), ccache behavior in debug mode is not changed.
With debug_level=1, ccache will only dump *.ccache-log files (and not the *input* ones). This is useful for getting per-file caching results.
Closes #1285
=> feat: Allow specifying debug level

src/argprocessing.cpp
cmake may generate both -include and -include-pch. Example:
c++ ... -Xclang -include-pch -Xclang /abs/path/cmake_pch.hxx.pch
-Xclang -include -Xclang /abs/path/cmake_pch.hxx ...
Both paths needs to be converted to relative path if CCACHE_BASEDIR is set for better cache hit rate in some CI systems.
=> fix: relative path handling for clang PCH header

src/InodeCache.cpp
As on FreeBSD 13.2 `statfs.f_bavail` is signed, so InodeCache.cpp cannot be compiled but gets a sign-compare warning:
src/InodeCache.cpp:409:30: error: comparison of integers of different signs:
'long' and 'unsigned long' [-Werror,-Wsign-compare]
if (buf.f_bavail * 512 < k_min_fs_mib_left * 1024 * 1024) {
~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~bareos
1 error generated.
The problem is avoided by using static_cast to unsigned long on FreeBSD. 
To detect FreeBSD, now `sys/param.h` is included unconditionally.
=> fix: src/InodeCache.cpp: avoid sign-compare warning on FreeBSD

src/util/path.cpp, unittest/test_util_path.cpp
Prevents `path::is_absolute_path(path)` from reading characters further than `path` string length.
=> fix: Windows is_absolute_path() crash on drive letter

CMakeLists.txt, cmake/StaticLinkSupport.cmake
Make linking dependent libraries as static a hard requirement when
STATIC_LINK is ON, as opposed to the previous behavior of falling back
to dynamic libraries.
A side-effect of this is that if only a dynamic zstd/hiredis is
available on a system, it will not be found, and the download and build
code will be invoked to build a static version from the internet.
Add a general case to handle Linux, macOS and similar by linking
libgcc/libstdc++ statically on gcc/clang.
Move the code into cmake/StaticLinkSupport.cmake and include it from the
main file.
Fix #1330
=> fix: cmake -DSTATIC_LINK=ON on Linux/macOS

CMakeLists.txt, cmake/Findhiredis.cmake, cmake/Findzstd.cmake, doc/INSTALL.md
Add the cmake option OFFLINE, defaulting to the value of the standard
variable FETCHCONTENT_FULLY_DISCONNECTED, which is OFF by default, to
disable downloading anything from the internet.
When ON, set FETCHCONTENT_FULLY_DISCONNECTED to ON, ZSTD_FROM_INTERNET
to OFF and HIREDIS_FROM_INTERNET to OFF.
When downloading is OFF and either library is not found, throw an error
using find_package_handle_standard_args().
Add the option to INSTALL.md doc.
=> feat: cmake -DOFFLINE=TRUE for offline builds

cmake/DevModeWarnings.cmake
MSVC apparently has overrides for the two definitions of operator== in
unittest/test_util_string.cpp in the <utility> header, raising a warning
about them being local unused functions:
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4505?view=msvc-170
Disable this warning type in cmake/DevModeWarnings.cmake for MSVC.
=> fix: devmode unused function warnings on new MSVC

src/argprocessing.cpp, src/compopt.cpp, unittest/test_compopt.cpp
add support for static analysis option in clang: --analyze
static analysis is performed separately from compilation and usually takes more time,
but its results can be captured the same way as regular compilation results: some
warnings may be printed and result is stored in .plist file instead of .o
this is partial solution for static analysis: -analyze option for cc1 is not supported
as I am macOS using Xcode, so modules are always enabled and I had to use direct mode
--analyzer-output option is also not supported, only default .plist format
I have not added much of the testing as I found no similar tests and not sure what would
be needed. If you provide some hints or guidance here I probably could fix that
=> (feat)add support for clang --analyze

src/ccache.cpp
This is my proposed fix for #1347.
clang-cl should still be detected as clang-cl when it's a symlink to clang.
=> fix: Detect symlink called clang-cl as clang-cl insted of normal clang

test/suites/direct.bash
There was a missing closing paren.
=> Fix regexp in direct.bash

.github/workflows/build.yaml
Split "Install dependencies" step into two.
Review without indentation change: https://github.com/ccache/ccache/pull/1359/files?diff=unified&w=1
`apt` is an interactive tool, not guaranteed to run without a terminal.
=> Use GHA feature in build.yaml

misc/typos.toml
Exclude false positives with context. So typos at other places will not be suppressed.
Latest `typos` does not detect any errors.
=> Properly exclude false positive typos

src/argprocessing.cpp
This is my proposed fix for https://github.com/ccache/ccache/issues/1364
=> fix: Use MSVC logic for clang-cl when handling precompiled header

doc/MANUAL.adoc, src/core/mainoptions.cpp
This adds a "machine readable" variant of `--show-log-stats`, similar to `--print-stats` as a variant of `--show-stats`.
See https://github.com/ccache/ccache/discussions/1379 and https://github.com/ccache/ccache/pull/1380.
=> feat: add `--print-log-stats`

doc/MANUAL.adoc, src/core/Statistic.hpp, src/core/Statistics.cpp, src/core/Statistics.hpp, src/core/mainoptions.cpp
This PR adds infrastructure to have selectable output format for `--print-stats`/`--print-log-stats`, and adds JSON format in addition to the previous (now default) tab separated format.
*edit* this is based on #1381
See #1379, #1380, #1381.
=> feat: add `--print-stats` format selection, JSON format

src/ArgsInfo.hpp, src/argprocessing.cpp, src/ccache.cpp, src/compopt.cpp, src/core/Result.cpp, src/core/Result.hpp, src/core/ResultRetriever.cpp, unittest/test_argprocessing.cpp
Fixes #1383 
This implements the /Yc (Create precompiled header) option of MSVC by caching the generated obj and pch files.
For me, this results in direct cache hits when testing with my demo repo: https://github.com/clemenswasser/ccache_pch_msvc_demo
```console
> ccache -s
Cacheable calls:      2 /   2 (100.0%)
Hits:               2 /   2 (100.0%)
```
The PR is currently marked as draft as it is currently missing any tests, etc. and is just a quickly hacked implementation.
=> Support for MSVC /Yc option

src/ccache/hashutil.cpp, src/ccache/util/file.cpp
Reading the file in do_hash_file as Bytes skips CRLF to LF conversion and is therefore way faster.
Optimize read_file size_hint on Windows by getting the file size of the existing handle instead of opening a duplicate one.
=> Read file in do_hash_file as Bytes and optimize read_file size_hint on Windows

src/ccache/util/LockFile.cpp, unittest/test_Util.cpp
MSYS2 will not let you create a symlink to a nonexistent file, only to an already existing file. To overcome this issue we use files, and write content on it. 
For Cygwin/MSYS2, the patch leverages POSIX `open` with the flags `O_WRONLY | O_CREAT | O_EXCL`, effectively creating an exclusive lock file. As suggested by @jrosdahl , thank you so much for the suggestion. 
This still does not pass the test suite, but makes ccache usable.
I look forward for you review.
See issue #1415
=> msys2 patch: lock mechanism uses file instead of symlink.

ci/build-macos-binary
We don't run the tests when building macOS universal binaries as its covered elsewhere so we can save some compile time by removing test builds.
=> ci: disable building test on macos binaries

cmake/GenerateConfigurationFile.cmake, cmake/config.h.in, src/ccache/util/file.cpp, unittest/test_util_file.cpp
Use sendfile for file copying as it avoids copying the data to user-space and back to kernel space.
=> feat: use sendfile(2) for file copying

.github/workflows/build.yaml
Updates macos images used. macOS-14 is M1 arm64. Macos11 has been deprecated and will be removed in june
=> ci: update macos images used

src/ccache/argprocessing.cpp, src/ccache/compopt.cpp, unittest/test_argprocessing.cpp
This PR further fixes the #1384. Fixes the case when the `/Yc` option is without the filepath and the `/Fppathname` is also defined.
The `/Yc` can be passed in two ways with and w/o the filepath. When it's passed w/o the filepath it must take the value of the `/Fp` option and if the `/Fp` option isn't defined then the resulting .pch file must have the same base name as the base source file with appended `.pch` extension (this case isn't handled correctly by ccache).
The `/Yc` option doesn't support passing a filepath with the space between like `/Yc filepath`. Because of this the `TAKES_ARG` must be removed. All occurrences of the [`compopt_takes_path()`](https://github.com/ccache/ccache/blob/911b899c6b51c3eb24e8b488361746ec590d2055/src/ccache/compopt.cpp#L279) can't be invoked for the …
=> fix: Handle -Yc without filepath for msvc

src/ccache/ArgsInfo.hpp, src/ccache/argprocessing.cpp, unittest/test_argprocessing.cpp
This PR depends on the previous one #1448.
It allows passing the `-Yc` option without the `-Fp` option and also without the `-Fo` option.
It sets the PCH filename from the base source file (`args_info.input_file`) and appends the `.pch` extension. This case is described in the [`/Yc`](https://learn.microsoft.com/en-us/cpp/build/reference/yc-create-precompiled-header-file?view=msvc-170) option documentation.
Similar logic is used to detect the `/Fo` filename, practically no changes were needed for this, all logic is already done [here](https://github.com/ccache/ccache/blob/master/src/ccache/argprocessing.cpp#L1413-L1417), only one change that was needed was to add the `get_default_pch_file_extension()` function that returns `.pch` for msvc like compilers.
The next addition is to return …
=> fix: Handle -Yc without -Fp and -Fo for msvc

src/ccache/compopt.cpp
/Fp and /Yu doesn't allow space between option and option value.
Fixes #1452
=> fix: TAKES_/CONCAT_ARG for msvc options

doc/MANUAL.adoc, src/ccache/core/mainoptions.cpp
I have added a new `--print-version` option as ccache will support PCH on msvc and I will need to somehow detect the ccache version to correctly decide if PCH should be disabled (`CMAKE_DISABLE_PRECOMPILE_HEADERS`). 
So if ccache >=4.10 then don't disable PCH and if it's below then set `CMAKE_DISABLE_PRECOMPILE_HEADERS=ON`.
=> feat: Add print-version option

cmake/GenerateConfigurationFile.cmake, cmake/config.h.in, src/ccache/hashutil.cpp
This should improve performance on all OSes. I thought I would convert hashing first and then `execute()` next, since it's slightly more complicated.
One question I have is whether there should be error handling on the `posix_spawn_file_actions_add*` functions, these seem very unlikely to fail (similar to `close` or `dup2` calls).
=> perf: Use posix_spawn when hashing

src/ccache/argprocessing.cpp, src/ccache/compopt.cpp
The arguments for the `--em-config` option for Emscripten were not being processed correctly, causing ccache to incorrectly interpret the following argument as an input file. This commit changes the argument processing function to correctly handle `--em-config` along with the required subsequent argument, improving compatibility with Emscripten's command line interface.
Fixes #1457
=> feat: Add argument handling for Emscripten's --em-config

src/ccache/argprocessing.cpp, src/ccache/ccache.cpp
These headers look unused I fastly looked over whole files for assert(), shared/unique_ptr<>, make_unique/shared<>, std::numeric_limits<>, and few other functions from cmath, and these files don't contain any, also checked #if macros for WIN32, Linux, and APPLE. (recompiled on Win and Linux gcc/clang, CI should catch this on any problem).
=> fix: removed unused headers

cmake/StandardSettings.cmake, unittest/CMakeLists.txt
Don't add the `/Zc:preprocessor-` compiler flag when it's not needed, to avoid the following warning: `D9025 : overriding '/Zc:preprocessor' with '/Zc:preprocessor-`
The latest Windows SDK `v10.0.22621` compiles fine with conforming preprocessor enabled, the bug was in older SDK-s like `<=10.0.20348.0`.
Also, add the /Zc:preprocessor for msvc `>=v19.25`, it didn't exist before this version (it existed as `/experimental:preprocessor` before), like is described [here](https://learn.microsoft.com/en-us/cpp/preprocessor/preprocessor-experimental-overview?view=msvc-170).
I tried to recompile ccache with older SDK-s `10.0.18362` and `10.0.20348.0`, and I didn't get any new compile errors or warnings without this `/Zc:preprocessor-` option, …
=> fix: Msvc /Zc:preprocessor warning

cmake/FindZstd.cmake
See:
```
$ git log --oneline  7e09f07b325b6e2a95e11776f23ff97716b7b924 -1
7e09f07b Fix Intel Xcode builds with assembly
$ git tag --contains 7e09f07b325b6e2a95e11776f23ff97716b7b924
v1.5.6
```
=> chore: zstd assembly fix is included in upstream version v1.5.6

cmake/FindCppHttplib.cmake
On Gentoo, the library name is 'httplib', not 'cpp-httplib'.
--
Note that I'm kind of submitting this as a POC patch. I'm not sure if the library name really is cpp-httplib or not on other distros. We're _not_ renaming it in Gentoo as far as I can tell, we're using upstream's CMake build (https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-cpp/cpp-httplib/cpp-httplib-0.15.3.ebuild).
If it really is cpp-httplib on other distros, some fallback will be needed instead. I can do that if desired.
=> build: Fix name of CppHttplib library

src/ccache/argprocessing.cpp
The nvcc (CUDA) compiler has a extra option compliant with -c: --compile. https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/#supported-phases
So ccache should see the --compile option as the -c option (especially because the CUDA MVS plugin use it!)
=> fix: Add the --compile option to be compliant with nvcc

test/suites/color_diagnostics.bash
The script program will try to run the --command parameter with the login shell,
rather than the currently running test shell (bash).
So if your login shell is set to a csh variant instead of a sh variant, you will get syntax errors from `CCACHE_DIR=$CCACHE_DIR`
Just set `SHELL=$BASH`:
```
ENVIRONMENT
The following environment variable is utilized by script:
SHELL  If  the variable SHELL exists, the shell forked by script will be that shell.  If SHELL is not set, the
Bourne shell is assumed.  (Most shells set this variable automatically).
```
=> fix: use bash for running script command

doc/MANUAL.adoc, src/ccache/storage/remote/httpstorage.cpp
This change adds the ability to send arbitrary http headers to the http backend storage. There are two main use cases:
1. An http server may require certain headers in order to process files correctly. For example, a server might require "content-type: application/octet-stream" to handle binary data.
2. It could be useful to collect metadata, such as the git commit id of branch being built, or the merge-base. This could be used to optimize the backend storage and/or collect metrics on usage.
=> feat: Add ability to send arbitrary http headers to http storage

src/ccache/core/common.cpp, src/ccache/core/common.hpp, unittest/test_core_common.cpp
=> feat: Option absolute_paths_in_stderr also rewrites relative paths in MSVC diagnostics messages

src/ccache/storage/remote/httpstorage.cpp
The changes introduced in dfcdb68 made it impossible to disable HTTP keep-alive
by setting the 'keep-alive' attribute in the backend string accordingly: The
default of 'true' is applied after parsing of the attributes, overriding the
value configured by the user (if any). Rectify this.
=> fix(http-storage): Make sure 'keep-alive' can be overridden as expected

test/suites/base.bash
Make tests pass in 2038
Fixes #1524
we use relative future timestamps to keep systems with 32-bit time_t working until 2037 (this should give them 1 year advance warning that they need to fix something).
Use the 3rd of January of the following year to ensure that it is in the future, even when starting a second before new year.
=> Make tests pass in 2038

doc/MANUAL.adoc, src/ccache/argprocessing.cpp, src/ccache/args.cpp, src/ccache/args.hpp, src/ccache/config.cpp, src/ccache/config.hpp, unittest/test_args.cpp, unittest/test_config.cpp
This PR implements a feature to fix a ccache issue we ran into.
Currently when a response file is seen on the command line the quoting behaviour is determined by the compiler type.
clang supports both windows and posix quoting via the `--rsp-quoting=[windows|posix]` option.
Due to NDA restrictions I cannot say what vendor we are using which is also why I cannot add a new compiler_type to special case this vendor's fork of clang.
We are building using a vendor clang to cross-compile to the vendor platform on windows. 
This vendor clang is effectively hardcoded with `--rsp-quoting=windows`.
The vendor MSBuild tasks emit response files with only windows quoting behaviour.
For everything else including the driver mode this vendor clang is clang, behaves like clang and uses clang options. It …
=> feat: Implement atfile_format config option to control rsp file format

src/ccache/argprocessing.cpp
When caching support for -fprofile-abs-path was added, the argument was omitted from the gcc commandline.
Fixes: 195011ad1b1f ("feat: Add support for GCC -fprofile-abs-path option")
=> fix: Pass -fprofile-abs-path through to gcc

doc/MANUAL.adoc, src/ccache/ccache.cpp, src/ccache/config.cpp, src/ccache/config.hpp
Intel's LLVM-based compilers are `icx` and `icx-cl`. Add support for them [based](https://github.com/ccache/ccache/pull/1100) on the changes that added support for Intel's legacy compiler, `icl`.
I noticed this because I was trying to use `ccache` with `icx` on Windows and it wasn't working. 
I didn't add a new enum for `icx-cl` because it can be treated exactly the same as `icx`.
Manually verified basic functionality.
=> feat: Add support for Intel's LLVM-based compilers

doc/MANUAL.adoc
`icx-cl` is available on Linux experimentally, so remove the statement that it is Windows only. It is still MSVC-compatible when used on Linux, so no code changes are required.
=> docs: Fix description of icx-cl

misc/clang-format
sha256sum requires explicitly using `-` as the input file on macOS.
Fixes https://github.com/ccache/ccache/issues/1542.
=> fix: correctly call sha256sum on macOS

src/ccache/storage/local/localstorage.cpp, src/ccache/storage/local/localstorage.hpp
1. Use hardlink and local storage to get raw files
2. Have enough files to surpass the 2K file limit in subdir
3. Create any new file in cache
The following files were created:
```
ccache/3/a/6/egahqp3b885sbmkb0t7eo365egbcm0R
ccache/3/a/6/6egahqp3b885sbmkb0t7eo365egbcm00W
```
Note the prefix "6" for the raw file, which should be removed as it is now in the subdir name.
On a new compile of the same file, the result file is reloaded, but it fails to find the raw file, triggering a recompile.
```
[2025-02-25T10:28:18.478066 12520] Retrieved 3a6egahqp3b885sbmkb0t7eo365egbcm0 from local storage (ccache/3/a/6/egahqp3b885sbmkb0t7eo365egbcm0R)
[2025-02-25T10:28:18.478233 12520] Reading raw entry #0 .o (482688 bytes)
[2025-02-25T10:28:18.478382 12520] Failed to lstat …
```
=> fix: LocalStorage::move_to_wanted_cache_level renamed raw files incorrectly, without recalculating full hash filename with new prefix (#1570)

src/ccache/compopt.cpp
Clang has a feature where it can compress compiler products such as object files, and this includes when it is just called to preprocess the input file.
Ccache expects to be able to process the output of the preprocessor and is not expecting a compressed binary file. Obvious symptoms are apparently random data in log messages, but ccache appears to produce random results.
The fix is to remove any "--offload-compress" options using the existing facilities when preprocessing.
=> fix: do not use --offload-compress when preprocessing

dockerfiles/alpine-3.11/Dockerfile, dockerfiles/alpine-3.15/Dockerfile, dockerfiles/debian-11/Dockerfile, dockerfiles/debian-12/Dockerfile, dockerfiles/fedora-36/Dockerfile, dockerfiles/fedora-40/Dockerfile, dockerfiles/ubuntu-22.04/Dockerfile, dockerfiles/ubuntu-24.04/Dockerfile
This change refreshes dockerfiles, so that they actually work. This includes:
- Fix: E: Package 'gcc-multilib' has no installation candidate in ubuntu*.
- CentOS images are EOLed.
- Add Debian 12.
It also includes a change to allow BASE_IMAGE to be overridden, this is just a convenience hook for cases when someone wants to use some other version of the base image (or add ccache into an existing custom image that is derived from those).
It also add name to a layer, so again it's easy to extend and build upon, since someone who uses this image is probably just going to pull one or few binaries and throw out the rest.
=> Refresh dockerfiles.

src/ccache/argprocessing.cpp, src/ccache/argsinfo.hpp, src/ccache/ccache.cpp, src/ccache/compopt.cpp, test/suites/basedir.bash, unittest/test_argprocessing.cpp
Follow up PR from the discussion here: https://github.com/ccache/ccache/discussions/1566
Essentially, when building React Native under different directories, some flags are being used that are not made relative by ccache, thus caching doesn't work at all.
To resolve this I made the following change:
- Add `make_relative_path` calls for: ivfsoverlay, fmodules-cache-path & fbuild-session-file
- Add unit tests for the flags above as well as a e2e test for fbuild-session-file
Opening this as a draft PR while I'm running some more local tests, would still appreciate any and all feedback though.
=> enhance: Support relative paths necessary for react-native builds in different directories

.github/workflows/codeql-analysis.yaml
This workflow throws a deprecation warning right now:
CodeQL Action major versions v1 and v2 have been deprecated. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/
=> ci: use CodeQL v3

cmake/StdAtomic.cmake
This patch is needed in order to link libatomic statically on debian arm/v5, where libatomic.a is required but it's hidden under subdirectory and is not visible to the normal linking process even with -static. This causes "static" ccache to depend on libatomic.so.
This option allows me to pass down location of the libatomic.a such as here: https://github.com/sobomax/ccache/blob/d12d99883661b766dc89c16766bdfac1b437295a/misc/get-arch-buildargs#L36
With this I have successfully implemented self-caching mechanism where ccache from a previous image build along with the previous cache set is used to speed-up build of the next revision. What is interesting, however is that effectiveness of this mechanism depends wildly between supported distros even for the same toolchain flavor/version between …
=> Link libatomic statically when STATIC_LINK is set

src/ccache/ccache.cpp
=> fix: using ccache and clang to compile CUDA code on Windows results empty preprocess file

src/ccache/util/file.cpp
When interpreting a char* string that is null terminated as wchar* string it is not guaranteed that the wchar* string is also null terminated. A char[3] string/memeory region with the content ['a', '\0', '\0', 100] interpreted as wchar* has no ending null character resulting in out of bounds memory reads when trying to construct a std::wstring from it.
=> read_file windows: Fix access violation

src/ccache/storage/remote/httpstorage.cpp
If the request fails and `result.error() != Error::Success` `result->` can return
a `nullptr` resulting in a null pointer dereference.
=> HttpStorageBackend::get: Logging: Fix read access violation

src/ccache/util/file.cpp
A missing return causes compilation failure.
=> fix: missing return
