ccache.c, ccache.h, hashutil.c, snprintf.c, test/framework.c, test/test_args.c, test/test_argument_processing.c, test/test_conf.c, test/test_hashutil.c, util.c
Mostly a quick hack to get the MinGW build working, and make the "quicktest" pass with Wine...
=> MinGW build for Windows

ccache.c
Commonly some base configuration like CFLAGS="-O2 -g3 ..." will be
modified for builds by appending "-g0" to disable debug information.
This commit only en/disables options based on the last argument
that modifies debuginfo generation.
Also some more arguments are supported.
PS. Some more work, but it would be usefull to "normalize" the commandline,
so some permutations of the identical arguments wont evade the cache.
Eg. take only the last argument when possible (like with the -g options) and then
define a normalized order.
=> Better parsing of g* Options, and only use last argument

ccache.h, stats.c
=> Show the time when stats were last zeroed out

src/ccache.c, src/hashtable.c
=> Address issues found by lgtm.com alerts

src/ccache.c
Some problems found after merging #280
=> Fix bugs in the newly introduced tracing mode

src/compopt.c, unittest/test_compopt.c
See https://clang-analyzer.llvm.org/
Closes #388
=> The clang --analyze option is too hard (for now)

src/ccache.c, test/suites/depend.bash, test/suites/direct.bash
This is sometimes used when detecting capabilities.
Closes #397
=> Support using -MF /dev/null argument

test/run
'ch' in cs_CZ locale is technically just one character, so directory
name 'ccache' fails the test
=> Fix make check with "funny" locales

Makefile.in, configure.ac, src/ccache.c, src/result.c, src/result.h, test/suites/base.bash, test/suites/cleanup.bash, test/suites/depend.bash, test/suites/direct.bash, test/suites/serialize_diagnostics.bash, test/suites/split_dwarf.bash
=> Add aggregated file storing all the results

.travis.yml, src/util.c, test/suites/cleanup.bash
Just created a PR for https://github.com/ccache/ccache/issues/442
=> Fix CCACHE_MAXSIZE with filesystem compression

.travis.sh, .travis.yml, .travis/Dockerfile, Makefile.in, configure.ac, dev.mk.in, src/hash.c, test/suites/base.bash, test/suites/direct.bash, unittest/test_hash.c
This is one third of #412
* Needs libb2 to be installed
* Removing mdfour is TODO
Based on previous ~#406~
=> Use BLAKE2b checksum instead of bundled MD4

src/ccache.cpp
Patch copied from jd-gascuel@f3b85c9
Fixes https://github.com/ccache/ccache/issues/454
=> Win32: make_relative_path also accept /c/users

.gitignore
Small patches that help keep the git repository clean in local clones
=> Misc buildsystem improvements

src/ccache.cpp
As discussed before, these are cleanups to the cc_reset function.
=> Small cleanup cc reset

src/ccache.cpp, src/compopt.cpp, unittest/test_compopt.cpp
Added test to detect the invalid case TOO_HARD | TAKES_CONCAT_ARG
=> Correct "-MJ" bail out, identify both "-MJ file" and "-MJfile"

src/ccache.c, src/manifest.c, src/manifest.h
details see: https://github.com/ccache/ccache/issues/493
=> Store mtime/ctime as -1 if sloppy_file_stat is not set

unittest/test_Config.cpp, unittest/test_ZstdCompression.cpp
This commit makes my ccache fork [Github actions pass](https://github.com/cristianadam/ccache/actions).
=> Unittest fixes on Windows

src/compress.cpp, src/legacy_util.cpp
Fixes: https://github.com/ccache/ccache/issues/530
=> Win32: Close reading file for recompression

Makefile.in, src/Stat.cpp, src/ZstdCompressor.cpp, src/ccache.cpp, src/cleanup.cpp, src/execute.cpp, src/exitfn.cpp, src/hash.cpp, src/hashutil.cpp, src/legacy_util.cpp, src/legacy_util.hpp, src/lockfile.cpp, src/logging.cpp, src/logging.hpp, src/manifest.cpp, src/result.hpp, src/stats.cpp
=> Move logging into separate file

src/ccache.cpp, src/legacy_globals.cpp, src/legacy_globals.hpp, unittest/test_argument_processing.cpp
Only the first changes a function signature, the rest are quite simple.
=> Context: move 7 more globals

src/Compression.cpp, src/Compression.hpp, src/Config.cpp, src/Config.hpp, src/Context.cpp, src/Context.hpp, src/ccache.cpp, src/ccache.hpp, src/compress.cpp, src/compress.hpp, src/execute.cpp, src/execute.hpp, src/hashutil.cpp, src/hashutil.hpp, src/legacy_globals.cpp, src/legacy_globals.hpp, src/manifest.cpp, src/manifest.hpp, src/result.cpp, src/result.hpp, src/stats.cpp, src/stats.hpp, unittest/framework.cpp, unittest/test_Compression.cpp, unittest/test_argument_processing.cpp, unittest/test_hashutil.cpp
Used the proof of concept #526 to decide between `Config&` or `Context&` if both were possible.
=> Context: g_config, stats_file and orig_args moved

src/ArgsInfo.hpp, src/ResultRetriever.cpp, src/ResultRetriever.hpp, src/argprocessing.cpp, src/ccache.cpp, src/compopt.cpp, src/manifest.cpp, test/suites/direct.bash, test/suites/pch.bash
=> Handle clang PCHs (#539)

src/Logging.cpp, src/ccache.cpp, src/stats.cpp
=> Update comments, remove references to old global variables

test/suites/inode_cache.bash
Skipped inode_cache test on NFS.
=> Skipped test on NFS #639

src/TemporaryFile.hpp, src/execute.cpp
=> Small fixes for the master branch

src/ccache.cpp, test/suites/base.bash, unittest/test_ccache.cpp
=> Support ccache ccache gcc

doc/CMakeLists.txt
=> Build and install man page by default

cmake/GenerateConfigurationFile.cmake, cmake/StandardSettings.cmake, src/third_party/blake3/CMakeLists.txt
=> Disable some AVX features on old Apple clang versions

src/ArgsInfo.hpp, src/argprocessing.cpp, src/ccache.cpp, test/suites/base.bash, unittest/test_argprocessing.cpp
Proof of concept to resolve #683.
However several points (see #683) are currently unclear.
=> Cache result even without object file

src/third_party/doctest.h
=> Fix building 32bit tests on macOS

src/Util.cpp, unittest/test_Util.cpp
Scenario:
- /tmp is a symlink to /private/tmp.
- Both apparent and actual CWD is /private/tmp/dir.
- A path (e.g. the object file) on the command line is /tmp/dir/file.o.
- Base directory is set up to match /tmp/dir/file.o.
Ccache then rewrites /tmp/dir/file.o into ../../private/tmp/dir/file.o,
which is correct but not optimal since ./file.o would be a better
relative path. Especially on macOS where, for unknown reasons, the
kernel sometimes disallows opening a file like
../../private/tmp/dir/file.o for writing.
Improve this by letting Util::make_relative_path try to match
real_path(path) against the CWDs and choose the best match.
Closes #724.
=> Make Util::make_relative_path able to find matches for canonical path

CMakeLists.txt, cmake/UseCcache.cmake, cmake/UseFastestLinker.cmake, doc/CMakeLists.txt
Clean build time on my slow laptop (this will not be comparable to yours, but for me it's reproducible across builds)
|Before|With ccache|With ccache and linker selection|
|--|--|--|
|48.3s|8.5s|5.6s (ld.gold)<br>5.5s (ld.lld)|
The goal here is not only to improve ccache compile times, but also to provide a template to others how to improve compilation times.
=> Faster compile times

src/CacheFile.hpp, src/Util.cpp, src/Util.hpp, src/cleanup.cpp, src/compress.cpp, unittest/test_Util.cpp
Trivial change which makes some code slightly more readable. No functional change.
=> Refactor: drop out parameter from get_level_1_files

LICENSE.adoc, src/Stat.cpp, src/Stat.hpp, src/system.hpp, src/third_party/win32/winerror_to_errno.h, unittest/test_Stat.cpp
`stat()` as implemented in msvcrt.dll (used by mingw-w64) has a number of flaws:
- `st_ino` is always 0 (so `Stat::same_inode_as` gives inaccurate results)
- other file attributes are queried from the parent directory instead of the file itself, and so can be incorrect/stale, e.g. if a file is modified via another hard link.
The implementation in the UCRT is slightly better -- it prefers to query attributes from the file itself if possible, but it still doesn't populate `st_ino` and can silently fall back to querying from the parent directory and giving stale results.
I don't believe the msvcrt.dll source is available (you have to infer its behaviour from e.g. Process Monitor) but the ucrtbase.dll source code is available in the Windows 10 SDK.
Write an implementation of `stat`/`lstat` …
=> Implement a better Stat::stat(), Stat::lstat() for Windows

src/argprocessing.cpp, test/suites/multi_arch.bash
=> Allow one -Xarch_* option that matches -arch

CMakeLists.txt, cmake/CcachePackConfig.cmake, cmake/CodeAnalysis.cmake, test/CMakeLists.txt
I'll file another PR updating `misc/test-all-systems`.
Fixes: #884
=> Require CMake 3.10

doc/MANUAL.adoc, src/storage/secondary/HttpStorage.cpp, src/storage/secondary/HttpStorage.hpp
=> HTTP storage: Implement timeout support

src/argprocessing.cpp, test/suites/multi_arch.bash
=> fix: Remove duplicate -Xarch second argument

src/argprocessing.cpp
It is used by msbuild.
Fixes #1018
=> msvc: support directory input for -Fo

test/suites/depend.bash
=> test: Fix typo in depend tests

test/suites/depend.bash
The first test exercices a relative path only identical generation.
The second test exhibits a known limitation when the same test case is done with an absolute path (depend file is wrong).
=> feat: add depend mode tests

src/util/file.cpp, unittest/test_util_file.cpp
Based on https://stackoverflow.com/a/69410299/764870.
=> fix: Remove usage of deprecated codecvt header

.github/workflows/build.yaml, test/run, test/suites/base.bash, test/suites/basedir.bash, test/suites/color_diagnostics.bash, test/suites/cpp1.bash, test/suites/debug_prefix_map.bash, test/suites/depend.bash, test/suites/direct.bash, test/suites/hardlink.bash, test/suites/modules.bash, test/suites/nocpp2.bash, test/suites/pch.bash, test/suites/profiling.bash, test/suites/profiling_gcc.bash, test/suites/remote_file.bash, test/suites/remote_http.bash, test/suites/remote_only.bash, test/suites/remote_url.bash, test/suites/serialize_diagnostics.bash, test/suites/split_dwarf.bash, test/suites/upgrade.bash
=> Make the tests work under Windows

.github/workflows/build.yaml
CI is missing a few compilers add those newer compilers.
=> ci: Add missing compilers

misc/download-redis, misc/upload-redis
Support any version of manifest and result
Skip over tmp dir and allow avoiding setnx
=> Cleanup redis helper python scripts a bit

cmake/Findzstd.cmake
=> third_party: update zstd to 1.5.5

src/execute.cpp
adds missing feature for usage in IDEs on Windows to abort the child compiler when ccache is killed by any means.
A similar behaviour is present on Posix systems by default.
Ccache has a signal handler that adds some cleanup.
This would require to hook some break functions on win32 as well.
I have no experience with that.
This helps to not wait for 10 Minutes until the compiler finishes naturally.
=> win32: automatically kill compiler subprocess

.github/workflows/build.yaml
Actually, there is no such thing as `matrix.config`.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
=> Remove matrix.config from build.yaml

.github/workflows/build.yaml
Just some minor CI improvements
=> Add new compilers to CI and update actions

src/argprocessing.cpp, test/suites/profiling_clang.bash, test/suites/profiling_gcc.bash
Fixes https://github.com/ccache/ccache/issues/1407
This option AFAICT should be simple as it only affects how the profile is updated
=> feat: add -fprofile-update support

LICENSE.adoc, src/third_party/blake3/blake3.c, src/third_party/blake3/blake3.h, src/third_party/blake3/blake3_dispatch.c, src/third_party/blake3/blake3_impl.h, src/third_party/blake3/blake3_neon.c
=> bump: update blake3 to v1.5.1

doc/MANUAL.adoc, src/ccache/Config.cpp, src/ccache/ccache.cpp, src/ccache/core/Sloppiness.hpp
Code to address some issues in #1421
=> feat: add sloppiness for incbin handling

src/ccache/util/file.cpp
Use copyfile for more efficient copying on OSX
=> feat: use copyfile(3) on apple systems

src/ccache/util/file.cpp
Copyfile improvement for windows
=> perf: use native windows copyfile

src/ccache/InodeCache.cpp, src/ccache/util/wincompat.hpp
Small fixes discovered during reviews.
=> fix: small fixes

src/ccache/ccache.cpp
Hi,
I feel that this commit https://github.com/ccache/ccache/commit/6b85822b50cc509b4d595bf89340bdf0da526dc9 did break in ccache 4.10 the fact of using a CCACHE_PREFIX command which is expected to be resolved as an executable found in $PATH.
My issue is easily reproduceable if you start a `fedora:rawhide` container with either podman or docker, and install ccache in it (as fedora rawhide uses ccache 4.10) and try to compile a simple empty C file:
```
> podman run -t -i --rm --pull=always fedora:rawhide                                                                                                                                            1:23PM
Trying to pull registry.fedoraproject.org/fedora:rawhide...
Getting image source signatures
Copying blob …
```
=> Fix finding the prefix command in the $PATH environment variable when it's not an absolute/relative path already.

src/ccache/execute.cpp
Like the change in #1451, this should improve performance on all OSes.
=> perf: Use posix_spawn to execute the compiler

.mailmap, doc/AUTHORS.adoc, doc/NEWS.adoc
=> chore: Correct my name

src/ccache/argprocessing.cpp
=> feat: Add support for MSVC /TC and /TP options

src/ccache/util/string.cpp, unittest/test_util_string.cpp
=> fix: replace_all

cmake/StandardSettings.cmake
=> build: Instruct MSVC to accept UTF-8 characters

src/ccache/ccache.cpp
MSVC /FC option causes the paths in diagnostics messages become absolute.
Convert them to relative to avoid leakage of workspace paths.
User can specify absolute_paths_in_stderr=true to convert them back to absolute.
=> feat: Relativize absolute paths within base_dir in MSVC diagnostics messages

unittest/test_ccache.cpp
Unittest for https://github.com/ccache/ccache/commit/2d44072b022bf560cfb11993438c9cfc5fff997d.
=> test: Add a unittest for the hard link based compiler detection

src/ccache/core/common.cpp, unittest/test_core_common.cpp
This PR fixes reported issue #1536
=> Fix issue #1536
